### ISSUE TITLE
Navi10 support on launch day?

### ISSUE THREAD

**Issue by oscarbg** [GPUOpen-Drivers/AMDVLK#101]
Hi,
just asking if we can expect an AMDVLK release on Navi launch day (7 july) or shortly after with support for 5700XT..

**Comment by jinjianrong** [comment]
We are doing IP scrub on the source code. Might be a little bit later than launch day.

**Comment by oscarbg** [comment]
thanks for status update..

**Comment by Degerz** [comment]
@jinjianrong Additionally, can we also have a documentation of the Navi ISA and especially the 3D/Compute register reference guide ? (the [last](http://developer.amd.com/wordpress/media/2013/10/CIK_3D_registers_v2.pdf) time I remember AMD releasing register reference guide was the sea islands generation)

**Comment by oscarbg** [comment]
+1 on Navi ISA ..

**Comment by Degerz** [comment]
@jinjianrong Thanks for releasing [documentation](https://gpuopen.com/compute-product/amd-rdna-1-0-instruction-set-architecture/) on the Navi ISA. It would be very nice if we got the register reference guide for Navi as well ...
