### ISSUE TITLE
build fails because tagged MetroHash version is missing CMakeLists.txt 

### ISSUE THREAD

**Issue by horstderheld** [GPUOpen-Drivers/AMDVLK#113]
The tagged commit

`<project path="drivers/third_party/metrohash" name="MetroHash" revision="690a521d9beb2e1050cc8f273fdabc13b31bf8f6"/>`

doesn't have a CMakeLists.txt and build fails. Latest MetroHash commit works like expected.

**Comment by jaebaek** [comment]
I have the same issue.

**Comment by jinjianrong** [comment]
Thanks for the notice. We have corrected the revision. please check it.
