### ISSUE TITLE
SteamVR fails with error -202, compositor not fullscreen

### ISSUE THREAD

**Issue by yshui** [GPUOpen-Drivers/AMDVLK#114]
The error says

```
Headset Error
Make sure your headset's display is in fullscreen mode
```
Which doesn't make sense to me since steamvr is using direct mode.

This doesn't happen with RADV.

**Comment by yshui** [comment]
The behavior has changed with Q4.1.

The error no longer occurs, but in the HMD all i can see is static white rectangles on a black background. 

Should I close this issue and create a new one?

**Comment by jinjianrong** [comment]
Please create a new issue if there are still other problems
