### ISSUE TITLE
RPCS3 not working or hang

### ISSUE THREAD

**Issue by 4773n0x** [GPUOpen-Drivers/AMDVLK#116]
RPCS3 emulator with AMDVLK crashes or hangs on compiling shaders. Works fine with AMDGPU PRO Vulkan driver. I tried many different distros - Arch Linux, Ubuntu and others. It's all the same.

**Comment by 4773n0x** [comment]
Forgot - Graphics card is RX 5700 XT
No games will run with AMDVLK (any game)

**Comment by Pik-a-boo** [comment]
Try using RADV? :S

**Comment by jinjianrong** [comment]
@4773n0x where can we get a free game to test with the emulator?

**Comment by jinjianrong** [comment]
A fix is submitted for the issue: https://github.com/GPUOpen-Drivers/llpc/commit/a89972e59b5ca4aa16525526c211ac8bb9d33872
