### ISSUE TITLE
RHEL/CentOS 8.0 support?

### ISSUE THREAD

**Issue by wsphillips** [GPUOpen-Drivers/AMDVLK#118]
Has anyone reported success building/running the drivers for CentOS 8.0? Is official support planned for the near future?

**Comment by JacobHeAMD** [comment]
Are you running into build issue for CentOS 8.0? You can create an issue here if so.

**Comment by wsphillips** [comment]
No--precautionary inquiry as it wasn't listed as officially supported. Currently opting for Ubuntu 18.04 If I return to CentOS 8 in the future I will report any issues.
