### ISSUE TITLE
Crysis 1 with dxvk results in semi random artifacts

### ISSUE THREAD

**Issue by nicman23** [GPUOpen-Drivers/AMDVLK#120]
with latest and older versions of dxvk with recent mesa, starting a game (or loading a save) in Crysis 1 results artifacts.

radv on the other hand works.

**Comment by jinjianrong** [comment]
@nicman23 Thanks for reporting the issue. could you capture an image to show the issue? if possible, please help capture  renderdoc trace as well.

**Comment by nicman23** [comment]
pic: https://user-images.githubusercontent.com/16306097/67042704-189acb00-f131-11e9-80a5-90f98f54ebfd.jpeg

> capture renderdoc trace as well

sure no idea how to though. if you can point me to some documentation i ll do it

**Comment by ashleysmithamd** [comment]
@nicman23 Could you provide a few details of the system you are using, CPU, GPU. Whether you are using the steam version of the game, if so, the version of proton. Thank-you

**Comment by nicman23** [comment]
ryzen 2700, rx 580, arch linux mainline wine

i am using a disc version with all patches applied

**Comment by jinjianrong** [comment]
Please try 2021.Q3.2

**Comment by nicman23** [comment]
i do not have amd hardware atm
