### ISSUE TITLE
amdvlk build fails with -j22 but works with -j4

### ISSUE THREAD

**Issue by shmerl** [GPUOpen-Drivers/AMDVLK#122]
After working around bug #117 by adding
```
-Wno-error=deprecated
-Wno-error=deprecated-cop
```

to `drivers/pal/shared/gpuopen/cmake/AMD.cmake`, the build managed to go through, but it was still failing when using -j22 (Ryzen 9 3900X). It worked using less threads (like -j4).

Using g++ 9.2.1 in Debian testing.

**Comment by Johnnynator** [comment]
Can you provide a full failing build log?

**Comment by shmerl** [comment]
[build_log.zip](https://github.com/GPUOpen-Drivers/AMDVLK/files/3776634/build_log.zip)

**Comment by shmerl** [comment]
Actually, I think I know what's happening, it's not the fault of cmake or configuration - it simply run out of RAM. So closing.
