### ISSUE TITLE
The Surge 2 hangs with AMDVLK

### ISSUE THREAD

**Issue by Ahmed-E-86** [GPUOpen-Drivers/AMDVLK#125]
I can go the main menu of the game, but it hangs after pressing (New game)

GPU: AMD HD 8750M 2gb of vram
AMDVLK: v-2019.Q4.2
Driver: Mesa 19.3

**Comment by ahmed-elsayed2017** [comment]
The same issue still exists with v-2019.Q4.3.

**Comment by JaxLinAMD** [comment]
hang is not observed in new version of this game.

**Comment by Ahmed-E-86** [comment]
It happens after starting a new game. Anyway, the game works fine with amdgpu-pro 19.50
