### ISSUE TITLE
Control: Corrupted textures when using kernel ver. 5.0.0-37

### ISSUE THREAD

**Issue by Ahmed-E-86** [GPUOpen-Drivers/AMDVLK#128]
The latest stable kernel update for Ubuntu breaks AMDVLK (Kernel version **5.0.0-37**)

I use now kernel 5.3.0-24 which works fine with AMDVLK, but I wanted to report this issue, because a lot of distros are based on Ubuntu, and Ubuntu uses now Kernel version 5.0.0-37

**GPU:** AMD HD 8750M 2gb of vram
**AMDVLK:** v-2019.Q4.3
**Driver:** Mesa 19.3 rc5 (kisak-mesa PPA)
**OS:** Linux Mint Cinnamon 19.3

**Comment by jinjianrong** [comment]
We tried Kernel version 5.0.0-37 with Vega10, AMDVLK works well on it

**Comment by ahmed-elsayed2017** [comment]
I switched back to Kernel version 5.0.0-37 to do some testing.

**1- Control:**

![Screenshot from 2019-12-10 20-25-19](https://user-images.githubusercontent.com/29783425/70559489-665f0d00-1b8f-11ea-9863-84f7376db5c9.png)

**2- Darksiders Genesis:** (The shadows don't look good)

![Screenshot from 2019-12-10 20-29-55](https://user-images.githubusercontent.com/29783425/70559550-8d1d4380-1b8f-11ea-9be4-605132d18d15.png)

3- **Blacksad:** (Some textures failed to load) 

![Screenshot from 2019-12-10 20-36-43](https://user-images.githubusercontent.com/29783425/70559613-b1792000-1b8f-11ea-8d05-ab52364e8013.png)

I found out after closing Blacksad that the Ram almost full, so I decided to restart my machine, and that happened:

![IMG_20191210_204905](https://user-images.githubusercontent.com/29783425/70559815-01f07d80-1b90-11ea-9eb1-9a2cfe8c5370.jpg)

**Comment by ahmed-elsayed2017** [comment]
Actually the other 2 issues happens with RADV as well, but the corrupted textures only happens with Control when using kernel version 5.0.0-37. I will change the title to be more accurate.
