### ISSUE TITLE
info about VK_AMD_image_layout_resolve shipping on Catalyst 17.2.3..

### ISSUE THREAD

**Issue by oscarbg** [GPUOpen-Drivers/AMDVLK#14]
I say because may be eventually supported by AMDVLK,
 being a shared codebase..

**Comment by jinjianrong** [comment]
The extension will be added after the spec is ratified

**Comment by JacobHeAMD** [comment]
VK_AMD_image_layout_resolve is unnecessary now and will be deprecated even with amdgpu-pro.
