### ISSUE TITLE
Assassin's Creed Syndicate broken transparency

### ISSUE THREAD

**Issue by niobium93** [GPUOpen-Drivers/AMDVLK#145]
Running on Arch Linux Zen 5.5.9 kernel with Wine Staging 5.4 and DXVK 1.5.5 on the AMDVLK 2020.Q1.3-1 driver on an RX 5700 XT.
Screen capture: [https://www.youtube.com/watch?v=QEF1FC6dZgM](https://www.youtube.com/watch?v=QEF1FC6dZgM)
RenderDoc capture: [https://mega.nz/#!nBghiSIC!QCRnV_txLI2ASR_utuMNs8VL0IYUNRnjVhdsqYlwOJU](https://mega.nz/#!nBghiSIC!QCRnV_txLI2ASR_utuMNs8VL0IYUNRnjVhdsqYlwOJU)

**Comment by Kron4ek** [comment]
The same issue in Kingdom Come Deliverance on RX 560.

![kcd](https://user-images.githubusercontent.com/13851877/77266154-7aeb8f00-6cc0-11ea-8d85-f2467317b7de.png)

**Comment by jinjianrong** [comment]
@niobium93 There is a change for this issue in amd-gfx-gpuopen-dev branch of llvm-project. could you try it?

**Comment by niobium93** [comment]
@jinjianrong I tried the dev branch and it's fixed there!
![Screenshot_2020-03-23_15-52-12](https://user-images.githubusercontent.com/1523948/77333811-a5733180-6d2c-11ea-9c88-ed13c1d00b9a.png)
