### ISSUE TITLE
No VRR!

### ISSUE THREAD

**Issue by AlterDaddler** [GPUOpen-Drivers/AMDVLK#157]
Driver works nice for me but VRR does still not work in the latest release! 
This is an essential feature!

**Comment by libgradev** [comment]
Working fine here in v-2020.Q2.2

It's off by default, you can enable it in [amdPalSettings.cfg](https://github.com/GPUOpen-Drivers/AMDVLK#runtime-settings):

`EnableAdaptiveSync,1`

**Comment by AlterDaddler** [comment]
Sry for my bad post... it works with this settings :)
