### ISSUE TITLE
Multiple issues with Doom Eternal

### ISSUE THREAD

**Issue by Ahmed-E-86** [GPUOpen-Drivers/AMDVLK#166]
AMDVLK offers twice the performance I can get from RADV, but I encounter multiple issues:

**1- GPU sometimes hangs during loading, and after trying to force-restart my system, I get these errors:**

![IMG_20200627_132047](https://user-images.githubusercontent.com/29783425/85921431-9bf1ec00-b87c-11ea-9753-ad8d4cd814c8.jpg)

**2- GPU hangs after I break a cracked wall like the wall in this picture:**
_The same issue happens with amdgpu-pro-vulkan-driver_

![AMDVLK2](https://user-images.githubusercontent.com/29783425/85921447-bcba4180-b87c-11ea-90f3-72f47664a09f.png)

**3- I encounter an issue with the lighting when I am at the main menu:**

![AMDVLK](https://user-images.githubusercontent.com/29783425/85921498-0f93f900-b87d-11ea-8afa-526acd50f6f7.png)

**System specs:**

**CPU:** Intel Core I5 4200M

**GPU:** AMD HD 8750M 2gb vram

**Driver:** Mesa 20.2-git (Obiaf PPA)

**OS:** Kubuntu 20.04

**Kernel:** 5.7.5-xanmod

**Comment by jinjianrong** [comment]
@Ahmed-E-86 are you still seeing the issue with latest driver build?

**Comment by Ahmed-E-86** [comment]
> @Ahmed-E-86 are you still seeing the issue with latest driver build?

Yes.

**Comment by jinjianrong** [comment]
The game runs well now in our internal testing. Please help create a new issue if you still see issues
