### ISSUE TITLE
Desktop freeze ubuntu 18.04

### ISSUE THREAD

**Issue by ellenkampguus** [GPUOpen-Drivers/AMDVLK#167]
I am not sure where to go as I searched everywhere and tried all kinds of AMD drivers, but as soon as I install any AMD driver after a while my desktop freezes with the mouse still moving. I can also access my system through ssh, but when rebooting it sometimes hangs after/during reboot so I have to hard reset it.

The issue occurs mostly (always) when I try to move a window around, where parts of the screen are being copied.

If I resort to the 'lowest' video mode/driver I can find the screen is very slow and not really usable. But with the (faster) drivers the system hangs often. I tried different kernels, HWE, etc., etc., but nothing seems to work. I hope I can find a solution here.

Card info:

VCE feature version: 0, firmware version: 0x00000000
UVD feature version: 0, firmware version: 0x00000000
MC feature version: 0, firmware version: 0x00a37610
ME feature version: 29, firmware version: 0x00000091
PFP feature version: 29, firmware version: 0x00000054
CE feature version: 29, firmware version: 0x0000003d
RLC feature version: 1, firmware version: 0x0000001c
RLC SRLC feature version: 0, firmware version: 0x00000000
RLC SRLG feature version: 0, firmware version: 0x00000000
RLC SRLS feature version: 0, firmware version: 0x00000000
MEC feature version: 0, firmware version: 0x00000000
SOS feature version: 0, firmware version: 0x00000000
ASD feature version: 0, firmware version: 0x00000000
SMC feature version: 0, firmware version: 0x10020000
SDMA0 feature version: 0, firmware version: 0x00000000
SDMA1 feature version: 0, firmware version: 0x00000000
VCN feature version: 0, firmware version: 0x00000000
VBIOS version: 113-AD54600-100

**Comment by JacobHeAMD** [comment]
If the issue is seen even never running with vulkan application, I don't think it's caused by AMDVLK.
