### ISSUE TITLE
Several games refuses to launch with AMDVLK

### ISSUE THREAD

**Issue by kattjevfel** [GPUOpen-Drivers/AMDVLK#169]
~~Game launcher runs but main application crashes instantly, runs perfect with RADV.~~
I've now tested several games and most don't seem to run with AMDVLK.

Grand Theft Auto IV: [steam-12210.log](https://github.com/GPUOpen-Drivers/AMDVLK/files/4906872/steam-12210.log)
FlatOut Ultimate Carnage: [steam-12360.log](https://github.com/GPUOpen-Drivers/AMDVLK/files/4906892/steam-12360.log)
My Summer Car: [steam-516750.log](https://github.com/GPUOpen-Drivers/AMDVLK/files/4906893/steam-516750.log)
Borderlands 2: [steam-49520.log](https://github.com/GPUOpen-Drivers/AMDVLK/files/4906894/steam-49520.log)
Tomb Raider: [steam-203160.log](https://github.com/GPUOpen-Drivers/AMDVLK/files/4906910/steam-203160.log)

Arch Linux
AMD Ryzen 5 1600X
AMD Radeon RX Vega 56
16 GB RAM

amdvlk 2020.Q3.1
llvm 10.0.0
Proton 5.0-9

Launched with: `VK_ICD_FILENAMES=/usr/share/vulkan/icd.d/amd_icd32.json:/usr/share/vulkan/icd.d/amd_icd64.json PROTON_LOG=1 %command%`

**Comment by Flakebi** [comment]
As you are using arch, maybe you are hitting #165? amdvlk does not seem to work with mesa > 20.0.7-3 on some systems.

**Comment by kattjevfel** [comment]
@Flakebi It works just fine on some other games, both DXVK and native ones.
To name a few: Spyro: Reignited Trilogy, My Time At Portia, Divinity: Original Sin 2 and vkQuake.

**Comment by Flakebi** [comment]
Ok thanks, seems like something different then.

**Comment by JacobHeAMD** [comment]
@kattjevfel , did you uninstall radv before trying with AMDVLK?

**Comment by kattjevfel** [comment]
@JacobHeAMD No I kept RADV installed and launched the games with `VK_ICD_FILENAMES=/usr/share/vulkan/icd.d/amd_icd32.json:/usr/share/vulkan/icd.d/amd_icd64.json PROTON_LOG=1 %command%` which works just fine on other games, is this not the right way to do it?

**Comment by massatt212** [comment]
i wonder if AMDVLK will ever use ACO or can it ?

**Comment by JaxLinAMD** [comment]
AMDVLK can't use ACO for now and I don't think there are any plan of using ACO so far.

**Comment by jinjianrong** [comment]
Reproduced the issue with Grand Theft Auto IV. It is a regression

**Comment by JaxLinAMD** [comment]
@kattjevfel issue fixed in v-2020.Q3.5, please verify with it.

**Comment by kattjevfel** [comment]
@JaxLinAMD I tested Fallout 76, My Summer Car, FlatOut: Ultimate Carnage and GTA IV. Both F76 and MSC worked, but not the rest, the ones working being 64-bit, and the rest are 32-bit and refused to launch.

GTA IV: [steam-12210.log](https://github.com/GPUOpen-Drivers/AMDVLK/files/5233715/steam-12210.log)
FlatOut UC: [steam-12360.log](https://github.com/GPUOpen-Drivers/AMDVLK/files/5233717/steam-12360.log)
