### ISSUE TITLE
Little Witch Nobeta hard crash and attempt to reboot on RX 5700 XT

### ISSUE THREAD

**Issue by Awlexus** [GPUOpen-Drivers/AMDVLK#170]
## Brief summary of the problem:
  I was playing the demo for Little Witch Nobeta and as soon as I enter a specific area my Screen freezes.

## Hardware description:
 - **CPU:** AMD Ryzen 5 3600 (6C/12T)
 - **GPU:** AMD Radeon RX 5700 XT
 - **System Memory:** 15.6Gb
 - **Display(s):** x11 server: X.Org 1.20.8 driver: amdgpu resolution: 2560x1440~144Hz
 - **Type of Diplay Connection:** DP

## System infomration:
 - **Distro name and Version:** Arch Linux
 - **Kernel version:** 5.7.7.arch1-1
 - AMD Packages installed
   * **local/amd-ucode 20200519.8ba6fa6-1** - Microcode update files for AMD CPUs
   * **local/amdvlk 2020.Q3.1-1** - AMD's standalone Vulkan driver
   * **local/lib32-amdvlk 2020.Q3.1-1** - AMD's standalone Vulkan driver
   * **local/opencl-mesa 20.1.3-1** - OpenCL support for AMD/ATI Radeon mesa drivers
   * **local/xf86-video-amdgpu 19.1.0-2 (xorg-drivers)** - X.org amdgpu video driver

## Attached files:
 - [amd_crash.log](/uploads/1abe7c6217bb5fd296b713b2633de0c9/amd_crash.log)
 - [xorg.log](/uploads/4cc744bc2744d2ea842d3dd2ef681aa5/xorg.log)

moved from https://gitlab.freedesktop.org/mesa/mesa/-/issues/3268

**Comment by JaxLinAMD** [comment]
@Awlexus issue is fixed in v-2020.Q3.6, please try that release
