### ISSUE TITLE
v-2020.Q3.4 cannot compile spvgen.so | "glslang/build_info.h" file not found

### ISSUE THREAD

**Issue by DiabeticCrab** [GPUOpen-Drivers/AMDVLK#178]
/home/user/git/amdvlk/drivers/spvgen/source/spvgen.cpp:72:10: schwerwiegender Fehler: glslang/build_info.h: Datei oder Verzeichnis nicht gefunden
   72 | #include "glslang/build_info.h"
      |          ^~~~~~~~~~~~~~~~~~~~~~
Kompilierung beendet.
[31/182] Building CXX object spvgen/external/SPIRV-tools/source/CMakeFiles/SPIRV-Tools.dir/val/validate.cpp.o
ninja: build stopped: subcommand failed.
make: *** [Makefile:77: spvgen64.so] Fehler 1

I am having this issue when trying to make a 64bit release build of spvgen.so on Gentoo. Previous versions, including v-2020.Q3.3 work fine. For compilation, I use a [master makefile](https://github.com/GPUOpen-Drivers/AMDVLK/files/5119138/Makefile.txt), that fetches the sources and sets up the build environment. I'll attach this aswell.

EDIT: Updated and polished the master makefile; maybe you want to distribute it as an easier way to build the driver?

**Comment by JaxLinAMD** [comment]
@DiabeticCrab, at the time you open this ticket, the final revision of v-2020.Q3.4 is not merged to master branch, also, please delete spvgen sources and fetch again. "ninja glslang", this is not needed, you can remove that from makefile you write.

**Comment by DiabeticCrab** [comment]
>at the time you open this ticket, the final revision of v-2020.Q3.4 is not merged to master branch
I see.
> delete spvgen sources and fetch again ... "ninja glslang" ... not needed
Thanks, this fixed the issue. I updated the [Makefile](https://github.com/GPUOpen-Drivers/AMDVLK/files/5178284/Makefile.txt)
 accordingly to automate this when switching between branches. The glslang entry was there as an attempt to workaround the issue but it didn't help anyway. It is now removed.
