### ISSUE TITLE
v-2020.Q3.4 is missing a release announcement, or actual packages for Ubuntu/RHEL.

### ISSUE THREAD

**Issue by kleinerm** [GPUOpen-Drivers/AMDVLK#180]
A look at

https://github.com/GPUOpen-Drivers/AMDVLK/releases/tag/v-2020.Q3.4

will make this obvious. But also see https://github.com/GPUOpen-Drivers/pal/issues/46 for another screwup in the current release branches which you may want to fix first.

thanks.

**Comment by JaxLinAMD** [comment]
We encounter some problems after promoting code to master branch, will release the package after all issues are fixed.
