### ISSUE TITLE
Sparse residency support

### ISSUE THREAD

**Issue by Vincent-P** [GPUOpen-Drivers/AMDVLK#181]
Hello,
I am trying to implement a sparse shadow map in Vulkan, it seems possible in DirectX with tiled resources and OpenGL with ARB_sparse_texture.
However from what i saw in xgl's `vkGetPhysicalDeviceFormatProperties(3)` and pal  `prtFeatures`, sparse depth formats doesn't seem to be supported with the vulkan driver.
Is it a hardware limitation or just a feature missing from Vulkan? I am using a RX 5700XT with the latest drivers.

**Comment by Vincent-P** [comment]
Maybe the question wasn't clear enough, does any devices supports the flag `PrtFeatureImageDepthStencil`?
If not, isn't it possible to create DSV with a tiled resource in DirectX11 or a depth buffer with the `TEXTURE_SPARSE_ARB` flag in OpenGL?
If so, I find it weird that something that is possible with DirectX and OpenGL isn't possible in Vulkan as well.

**Comment by Degerz** [comment]
> If not, isn't it possible to create DSV with a tiled resource in DirectX11 or a depth buffer with the TEXTURE_SPARSE_ARB flag in OpenGL?
If so, I find it weird that something that is possible with DirectX and OpenGL isn't possible in Vulkan as well.

No it isn't because sparse depth and stencil formats are also made optional in D3D11 and OpenGL. In no way are AMD required to support these formats in any APIs ... 

Creating sparse resources with these formats will likely cause an application crash or an undefined behaviour on AMD HW ...

**Comment by qiaojbao** [comment]
I test some CTS for sparse image, it seems all passed.
./deqp-vk -n dEQP-VK.api.info.sparse_image_format_*.d*
Writing test log into TestResults.qpa
dEQP Core git-705b50213572e57f29e84551436fabeafc937db7 (0x705b5021) starting..
  target implementation = 'Default'

Test case 'dEQP-VK.api.info.sparse_image_format_properties2.1d.optimal.d16_unorm'..
  Pass (Querying sparse image format properties succeeded)

Test case 'dEQP-VK.api.info.sparse_image_format_properties2.1d.optimal.d32_sfloat'..
  Pass (Querying sparse image format properties succeeded)

Test case 'dEQP-VK.api.info.sparse_image_format_properties2.1d.optimal.d16_unorm_s8_uint'..
  Pass (Querying sparse image format properties succeeded)

Test case 'dEQP-VK.api.info.sparse_image_format_properties2.1d.optimal.d24_unorm_s8_uint'..
  Pass (Querying sparse image format properties succeeded)

Test case 'dEQP-VK.api.info.sparse_image_format_properties2.1d.optimal.d32_sfloat_s8_uint'..
  Pass (Querying sparse image format properties succeeded)

Test case 'dEQP-VK.api.info.sparse_image_format_properties2.1d.linear.d16_unorm'..
  Pass (Querying sparse image format properties succeeded)

Test case 'dEQP-VK.api.info.sparse_image_format_properties2.1d.linear.d32_sfloat'..
  Pass (Querying sparse image format properties succeeded)

Test case 'dEQP-VK.api.info.sparse_image_format_properties2.1d.linear.d16_unorm_s8_uint'..
  Pass (Querying sparse image format properties succeeded)

Test case 'dEQP-VK.api.info.sparse_image_format_properties2.1d.linear.d24_unorm_s8_uint'..
  Pass (Querying sparse image format properties succeeded)

Test case 'dEQP-VK.api.info.sparse_image_format_properties2.1d.linear.d32_sfloat_s8_uint'..
  Pass (Querying sparse image format properties succeeded)

Test case 'dEQP-VK.api.info.sparse_image_format_properties2.2d.optimal.d16_unorm'..
  Pass (Querying sparse image format properties succeeded)

Test case 'dEQP-VK.api.info.sparse_image_format_properties2.2d.optimal.d32_sfloat'..
  Pass (Querying sparse image format properties succeeded)

Test case 'dEQP-VK.api.info.sparse_image_format_properties2.2d.optimal.d16_unorm_s8_uint'..
  Pass (Querying sparse image format properties succeeded)

Test case 'dEQP-VK.api.info.sparse_image_format_properties2.2d.optimal.d24_unorm_s8_uint'..
  Pass (Querying sparse image format properties succeeded)

Test case 'dEQP-VK.api.info.sparse_image_format_properties2.2d.optimal.d32_sfloat_s8_uint'..
  Pass (Querying sparse image format properties succeeded)

Test case 'dEQP-VK.api.info.sparse_image_format_properties2.2d.linear.d16_unorm'..
  Pass (Querying sparse image format properties succeeded)

Test case 'dEQP-VK.api.info.sparse_image_format_properties2.2d.linear.d32_sfloat'..
  Pass (Querying sparse image format properties succeeded)

Test case 'dEQP-VK.api.info.sparse_image_format_properties2.2d.linear.d16_unorm_s8_uint'..
  Pass (Querying sparse image format properties succeeded)

Test case 'dEQP-VK.api.info.sparse_image_format_properties2.2d.linear.d24_unorm_s8_uint'..
  Pass (Querying sparse image format properties succeeded)

Test case 'dEQP-VK.api.info.sparse_image_format_properties2.2d.linear.d32_sfloat_s8_uint'..
  Pass (Querying sparse image format properties succeeded)

Test case 'dEQP-VK.api.info.sparse_image_format_properties2.3d.optimal.d16_unorm'..
  Pass (Querying sparse image format properties succeeded)

Test case 'dEQP-VK.api.info.sparse_image_format_properties2.3d.optimal.d32_sfloat'..
  Pass (Querying sparse image format properties succeeded)

Test case 'dEQP-VK.api.info.sparse_image_format_properties2.3d.optimal.d16_unorm_s8_uint'..
  Pass (Querying sparse image format properties succeeded)

Test case 'dEQP-VK.api.info.sparse_image_format_properties2.3d.optimal.d24_unorm_s8_uint'..
  Pass (Querying sparse image format properties succeeded)

Test case 'dEQP-VK.api.info.sparse_image_format_properties2.3d.optimal.d32_sfloat_s8_uint'..
  Pass (Querying sparse image format properties succeeded)

Test case 'dEQP-VK.api.info.sparse_image_format_properties2.3d.linear.d16_unorm'..
  Pass (Querying sparse image format properties succeeded)

Test case 'dEQP-VK.api.info.sparse_image_format_properties2.3d.linear.d32_sfloat'..
  Pass (Querying sparse image format properties succeeded)

Test case 'dEQP-VK.api.info.sparse_image_format_properties2.3d.linear.d16_unorm_s8_uint'..
  Pass (Querying sparse image format properties succeeded)

Test case 'dEQP-VK.api.info.sparse_image_format_properties2.3d.linear.d24_unorm_s8_uint'..
  Pass (Querying sparse image format properties succeeded)

Test case 'dEQP-VK.api.info.sparse_image_format_properties2.3d.linear.d32_sfloat_s8_uint'..
  Pass (Querying sparse image format properties succeeded)

DONE!

Test run totals:
  Passed:        30/30 (100.0%)
  Failed:        0/30 (0.0%)
  Not supported: 0/30 (0.0%)
  Warnings:      0/30 (0.0%)
  Waived:        0/30 (0.0%)
