### ISSUE TITLE
[DXVK] Visual artefacts in Assassins Creed: Odyssey

### ISSUE THREAD

**Issue by Brisse89** [GPUOpen-Drivers/AMDVLK#185]
Visual artefacts in Assassins Creed: Odyssey using DXVK 1.7.1 and AMDVLK 2020.Q3.5:

GPU: R9 Fury

There is no issue when using the mesa radv driver, only when using amdvlk.

![Skärmbild från 2020-09-17 19-52-01](https://user-images.githubusercontent.com/10871070/93510148-12086b00-f921-11ea-925c-7d591d66e77d.png)

**Comment by Brisse89** [comment]
Not sure if this is any help, but I might as well mention it. I just upgraded to AMDVLK 2020.Q4.1 and the artefacts look different now. Those shown in the screenshot above are gone, and instead there are bright flashing colours.

**Comment by JaxLinAMD** [comment]
thanks for the update

**Comment by Brisse89** [comment]
Tested new release (AMDVLK 2021.Q1.1) and it now renders correctly, at least on my machine.

This issue can probably be closed now, but I'll leave it to you AMD-folks in case you want to do your own testing first.
