### ISSUE TITLE
incorrect image

### ISSUE THREAD

**Issue by JohnnyDilinjer** [GPUOpen-Drivers/AMDVLK#189]
Hello. When using AMDVLK, such a picture appears, when using RADV, the picture is correct.
How can I find the reason?
![mdvlk](https://user-images.githubusercontent.com/49310990/98132406-f536ef80-1eee-11eb-9fa9-a9d4ee99eeae.jpg)

**Comment by qiaojbao** [comment]
I can not reproduce it with Q4_2 AMDVLK on ubuntu 20.04.
Could you provide more info about your system and cards info?
Guess something wrong with Xserver (maybe others) framebuffer format.

**Comment by JohnnyDilinjer** [comment]
I have a not quite standard system. I just wonder how can I find the cause of this wrong picture?
![amdvlk](https://user-images.githubusercontent.com/49310990/98354002-b7eb7280-2052-11eb-989a-229e89094ee0.jpg)

**Comment by qiaojbao** [comment]
Maybe we can start at demo_create_surface and vulkan swap-chain.
