### ISSUE TITLE
[GL] Rendering to texture view ignores format

### ISSUE THREAD

**Issue by ReinUsesLisp** [GPUOpen-Drivers/AMDVLK#191]
When rendering to a framebuffer initialized like this:
```cpp
    glGenTextures(1, &texture_view);
    CreateTextures(GL_TEXTURE_2D, 1, &texture);
    TextureStorage2D(texture, 1, GL_R32F, 64, 64);

    TextureView(texture_view, GL_TEXTURE_2D, texture, GL_RGBA8, 0, 1, 0, 1);
    TextureParameteri(texture_view, GL_TEXTURE_MAG_FILTER, GL_NEAREST);

    GenFramebuffers(1, &framebuffer);
    BindFramebuffer(GL_DRAW_FRAMEBUFFER, framebuffer);
    FramebufferTexture(GL_DRAW_FRAMEBUFFER, GL_COLOR_ATTACHMENT0, texture_view, 0);
```
The texture view format `RGBA8` is ignored by the driver when rendering.

Here's a [Windows executable](https://github.com/GPUOpen-Drivers/AMDVLK/files/5605142/texture-views.zip) to reproduce the bug, and a [Visual Studio project](https://github.com/GPUOpen-Drivers/AMDVLK/files/5605146/texture-views-vcxproj.zip) to build and edit the same repro case.

The expected output is:
![imagen](https://user-images.githubusercontent.com/26564870/100393861-dde4b100-3019-11eb-836a-579d292b26dd.png)

And what the driver is currently emitting:
![imagen](https://user-images.githubusercontent.com/26564870/100393867-e4732880-3019-11eb-83ef-325ab88c7713.png)

If this is not the place to report OpenGL bugs, please close this issue. I took the freedom to report it here since another OpenGL issue has been accepted in the past.

**Comment by jinjianrong** [comment]
The issue is forwarded to our OGL team. You can report OpenGL driver issues on https://community.amd.com/t5/opengl-vulkan/bd-p/opengl-and-vulkan-discussions
