### ISSUE TITLE
Many DXVK games display transparent artifacts all over the screen when using AMDVLK with MSAA turned on.

### ISSUE THREAD

**Issue by niobium93** [GPUOpen-Drivers/AMDVLK#192]
Specs:
Arch Linux
AMD Radeon Rx 5700 XT
Kernel: 5.9.10-zen
AMDVLK 2020.Q4.5
DXVK v1.7.2-26-ge79e8b90
wine-tkg-staging-fsync-git-5.22.r5.g991f2e8e-309
![2020-11-29-06:02:38-screenshot](https://user-images.githubusercontent.com/1523948/100534115-5911b700-3214-11eb-8afb-2e28a9de73cd.png)
![2020-11-29-07:13:13-screenshot](https://user-images.githubusercontent.com/1523948/100534118-5ca53e00-3214-11eb-8388-71a5c22e0ad0.png)
![2020-11-29-07:14:06-screenshot](https://user-images.githubusercontent.com/1523948/100534122-5f079800-3214-11eb-86eb-7b65f40918f6.png)
![2020-11-29-07:19:22-screenshot](https://user-images.githubusercontent.com/1523948/100534126-629b1f00-3214-11eb-83bf-eafe39df6871.png)
![2020-11-29-07:21:48-screenshot](https://user-images.githubusercontent.com/1523948/100534128-64fd7900-3214-11eb-901b-2afb7786d876.png)
Games in order: Myst Online Uru Live, Call of Duty Modern Warfare 2, Horizon Chase Turbo, Call of Duty 4, Trackmania United Forever.
Most of these are D3D9 games with the exception of Horizon Chase Turbo which uses D3D11. Many other D3D11 games work fine though.

**Comment by aufkrawall** [comment]
Does the issue occur only with MSAA? I'm seeing a similar issue with MSAA across several games on Navi 10, e.g. Mirrors' Edge (2009 Unreal Engine 3). This wasn't broken on Polaris.

**Comment by niobium93** [comment]
[Yep! That's what's causing it.](https://www.youtube.com/watch?v=r2NatAtkIgM)
Tried with Trackmania and COD4 too. It's only broken with MSAA.

**Comment by aufkrawall** [comment]
Issue is fixed here with v-2021.Q1.1.

**Comment by niobium93** [comment]
Yep, fixed with 2021.Q1.1.
