### ISSUE TITLE
repo.radeon.com missing packages

### ISSUE THREAD

**Issue by dpanter** [GPUOpen-Drivers/AMDVLK#193]
amdvlk.list entry:
`deb [arch=amd64,i386] http://repo.radeon.com/amdvlk/apt/debian/ bionic main`

apt console output (truncated):
```
Err:26 http://repo.radeon.com/amdvlk/apt/debian bionic Release
  404  Not Found [IP: 13.82.220.49 80]
E: The repository 'http://repo.radeon.com/amdvlk/apt/debian bionic Release' no longer has a Release file.
```

Web browser -> https://repo.radeon.com/amdvlk/apt/debian
**404 Not Found** (same with http)

Ran apt update yesterday without errors. Something ate the files?

**Comment by JaxLinAMD** [comment]
@dpanter fixed now
