### ISSUE TITLE
Ray Tracing Hit Token ? 

### ISSUE THREAD

**Issue by Degerz** [GPUOpen-Drivers/AMDVLK#197]
Are there any plans to expose similar functionality on Vulkan since it's [available](https://github.com/GPUOpen-LibrariesAndSDKs/AGS_SDK/commit/4f2442c13eec0e8cb4feeef1185861ae99a13a9d) on D3D12 with driver extensions ?

**Comment by JaxLinAMD** [comment]
@Degerz  sorry, can't tell you details here, but you will see related commits on github when it is released.
