### ISSUE TITLE
WX x200 support

### ISSUE THREAD

**Issue by remi-sc** [GPUOpen-Drivers/AMDVLK#198]
Hi,
I noticed a conspicuous absence of Radeon™ Pro WX x200 Series support in the readme.
Is this correct and those cards are unsupported?

WX 3200 and 8200 seems basically a minor iteration on WX 3100 and 9100 (same architecture, slightly more CUs/faster clocks).
So I would guess that they could work.

**Comment by JaxLinAMD** [comment]
fixed.
