### ISSUE TITLE
DCC incorrectly enabled for certain format lists

### ISSUE THREAD

**Issue by pendingchaos** [GPUOpen-Drivers/AMDVLK#204]
It seems AMDVLK and AMDGPU-PRO enable DCC for images if a compatible integer format with a different sign than `VkImageCreateInfo::format` appears in `VkImageFormatListCreateInfo::pViewFormats` before an incompatible format. Reordering the format list so that the incompatible format is before the compatible format disables DCC.

The issue can be observed with this program: https://gist.github.com/pendingchaos/53f88567390a7df936a46dc7c518eb08

AMDVLK 2021.Q1.4:
```
driverVersion: 8388785
deviceName: Unknown AMD GPU
driverName: AMD open-source driver
       UINT,SINT: dcc
UINT,SFLOAT,SINT: nodcc
UINT,SINT,SFLOAT: dcc

driverVersion: 8388785
deviceName: Radeon RX 580 Series
driverName: AMD open-source driver
       UINT,SINT: dcc
UINT,SFLOAT,SINT: nodcc
UINT,SINT,SFLOAT: dcc
```

AMDGPU-PRO 20.45:
```
driverVersion: 8388766
deviceName: Unknown AMD GPU
driverName: AMD proprietary driver
       UINT,SINT: dcc
UINT,SFLOAT,SINT: nodcc
UINT,SINT,SFLOAT: dcc

driverVersion: 8388766
deviceName: Radeon RX 580 Series
driverName: AMD proprietary driver
       UINT,SINT: dcc
UINT,SFLOAT,SINT: nodcc
UINT,SINT,SFLOAT: dcc
```

"Unknown AMD GPU" is a Radeon RX 6800.

It seems the cause of this issue is that PAL's `Device::ComputeDccFormatEncoding` exits the loop as soon as a compatible integer format with a different sign is found, before it can check the compatibility of the rest of the formats.

This issue occurs when a Direct3D application under DXVK uses certain typeless formats such as `DXGI_FORMAT_R32_TYPELESS`. Trine 4: The Nightmare Prince is an example of this, though it appears enabling DCC for these formats does not cause obvious issues for this game.

**Comment by jinjianrong** [comment]
Fixed in 2021-Q2.2
