### ISSUE TITLE
VK_KHR_timeline_semaphore extension missing on  v-2021.Q1.4 

### ISSUE THREAD

**Issue by TomatDividedBy0** [GPUOpen-Drivers/AMDVLK#208]
I ran into an error using Yuzu with AMDVLK on this version, the log returned this error:

`[ 325.861822] Render.Vulkan <Error> video_core/vulkan_common/vulkan_device.cpp:CheckSuitability:542: Missing required extension: VK_KHR_timeline_semaphore`
`[ 325.878627] Render.Vulkan <Error> video_core/renderer_vulkan/renderer_vulkan.cpp:RendererVulkan:121: Vulkan initialization failed with error: VK_ERROR_EXTENSION_NOT_PRESENT`
`[ 325.879494] HW.GPU <Error> video_core/video_core.cpp:CreateGPU:50: Failed to initialize GPU: Vulkan initialization error VK_ERROR_EXTENSION_NOT_PRESENT`

I got confirmation from someone using an older version that they weren't running into the issue, but could replicate it on the current version of AMDVLK. I suspect there might be something wrong with the package.

**Comment by jinjianrong** [comment]
What version of Linux kernel are you using?  please refer to the notes in README: https://github.com/GPUOpen-Drivers/AMDVLK#known-issues
