### ISSUE TITLE
Support for VK_KHR_workgroup_memory_explicit_layout

### ISSUE THREAD

**Issue by ReinUsesLisp** [GPUOpen-Drivers/AMDVLK#212]
I'd like to ask if support for [VK_KHR_workgroup_memory_explicit_layout](https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VK_KHR_workgroup_memory_explicit_layout.html) is planned. The extension expresses the intended usage is for OpenCL layering, but it's also useful for other emulation purposes.

At the moment, if this extension is not available and an int8 or int16 store is needed we have to implement it with a CAS loop calling bitfield insert inside it. This spinning can have a negative impact on performance.

**Comment by Degerz** [comment]
I think this issue can be closed now with the latest release.

**Comment by amdrexu** [comment]
Thank you for confirmation.
