### ISSUE TITLE
[Linux] Dota 2 (amdvlk video driver) with vulkan api eat all system memory and hangs my PC (Manjaro Linux)

### ISSUE THREAD

**Issue by koreanfan** [GPUOpen-Drivers/AMDVLK#213]
System: https://gist.github.com/koreanfan/88412b48768bbbae6cdcf9b74f1f48b7
vulkan driver: amdvlk 2021.Q1.5-1
I want just play Dota 2 with vulkan api, but Dota 2 with vulkan eat all RAM ( at start- 3.5 GB, before crash pc - almost 8GB) and pc can hangs or even crash. With mesa opengl api dota eat at start - 3.5 GB, and after playing dota 2 eat max 4.5 GB. With radv driver dota 2 eat ram too and have same issue.

Steps for reproducing this issue:
Launch steam, launch dota 2 with command: -novid -vulkan
Launch task manager and dota 2 eat 3.5 GB of RAM
Play some matches. With every match dota eat more ram. When match is ended match results table loads very slow.
Switch to task manager and dota 2 eat almost all 8 GB of RAM
Play another some matches and pc can hangs, or just launch program (opera or another browser) and pc crash
Hard reset

**Comment by Flakebi** [comment]
As this problem happens with different drivers (radv and amdvlk), this is unlikely to be a driver problem and very likely to be a problem of Dota 2 (https://github.com/ValveSoftware/Dota-2-Vulkan/issues/370).
