### ISSUE TITLE
Please stop disabling RADV by default.

### ISSUE THREAD

**Issue by kelepiradam** [GPUOpen-Drivers/AMDVLK#218]
New switchable graphics behavior disables RADV and AMDVLK becomes the default however this behavior kills the performance of some desktop applications that rely on default hardware accelerated vulkan driver such as libreoffice using google skia to render using vulkan. 

Please do not change the default behavior and let RADV be the GPU0 the default driver again. Or many will start complaining about this behavior.

**Comment by jinjianrong** [comment]
The assumption is if users install the amdvlk package, they want to run amdvlk by default. For experienced users, they could switch to use RADV by setting AMD_VULKAN_ICD =  RADV. 
We will try to tune the amdvlk performance for google skia.
