### ISSUE TITLE
Deb package files installed with user as owner instead of root

### ISSUE THREAD

**Issue by Dantali0n** [GPUOpen-Drivers/AMDVLK#224]
Hello,

the Debian packages available under releases install the files with the system user as owner instead of root.

```
$ ls -lah /etc/vulkan/icd.d/
total 12K
drwxr-xr-x 2 root      root      4,0K apr 20 10:17 .
drwxr-xr-x 5 root      root      4,0K apr 10  2020 ..
-rw-rw-r-- 1 user      user  645 apr  7 13:13 amd_icd64.json
```

```
$ ls -lah /usr/lib/x86_64-linux-gnu/amdvlk64.so
-rwxrwxr-x 1 user user 56M apr  7 13:13 /usr/lib/x86_64-linux-gnu/amdvlk64.so
```

Operating system: Ubuntu 18.04
Steps to reproduce:

```
wget https://github.com/GPUOpen-Drivers/AMDVLK/releases/download/v-2021.Q2.1/amdvlk_2021.Q2.1_amd64.deb
sudo dpkg -i amdvlk_2021.Q2.1_amd64.deb
```

Expected behavior:

Files installed in the /etc and /usr folder should be owned by root not a regular system user.

Needless to say, this poses a security issue as any process from this regular user can modify these system files that will be used by any vulkan context.

**Comment by JaxLinAMD** [comment]
fixed
