### ISSUE TITLE
Red Dead Redemption 2 crashes at launch when vkBasalt is used with AMDVLK

### ISSUE THREAD

**Issue by aufkrawall** [GPUOpen-Drivers/AMDVLK#225]
Install wine-staging 6.6, Rockstar Games Launcher and then Red Dead Redemption 2. The game successfully starts

-with AMDVLK (open and pro) as long as vkBasalt isn't used. 
-with RADV + vkBasalt

The game crashes at launch when AMDVLK (open and pro) and vkBasalt are used at the same time. For example:

```
export VK_ICD_FILENAMES="/opt/amdgpu-pro/etc/vulkan/icd.d/amd_icd64.json:/opt/amdgpu-pro/etc/vulkan/icd.d/amd_icd32.json"
cd "/home/user/.wine/drive_c/Program Files/Rockstar Games/Launcher"
export ENABLE_VKBASALT=1
wine Launcher.exe
```

Program versions:
vkBasalt v0.3.2.4: https://github.com/DadSchoorse/vkBasalt/tags
amdvlk-open 2021.Q2.1 & amdvlk-pro 21.10.1247438
wine-staging 6.6
RX 6800, Linux 5.12-rc8

**Comment by jinjianrong** [comment]
@aufkrawall could you help check if the issue is still reproducible with  2021.Q3.2 build?
