### ISSUE TITLE
Linux Mint 18.3 report issue in Vulkaninfo

### ISSUE THREAD

**Issue by paladin4fan** [GPUOpen-Drivers/AMDVLK#23]
There is a line shows the message below:
amdvlk32.so: wrong ELF class: ELFCLASS32

**Comment by JacobHeAMD** [comment]
Did you install the 32bit AMDVLK driver although the vulkaninfo is 64bit? If so, it's not a bug of driver. It's a behavior of loader, which should not report this kind of message at all.  Anyway, it's not a true error. Please uninstall 32bit AMDVLK driver if you don't want to live with this message.

**Comment by paladin4fan** [comment]
Oh, that's fine. I installed the 32bit driver and just run the vulkaninfo in 64bit environment.
So it is not a true error, I think there is nothing to be worry about
