### ISSUE TITLE
Windows on ARM, Support?

### ISSUE THREAD

**Issue by sidd-kishan** [GPUOpen-Drivers/AMDVLK#232]
We can help you test we have Windows on Rasberry Pi 4 B+ setup. Please pursue it we at Windows on Rasberry Pi community will be glad to extend support in testing your drivers and tools for ARM64.

**Comment by Flakebi** [comment]
Sorry, this is just a Linux driver, so neither Windows nor Windows on ARM support.

However, I’d be really interested to see a picture of your Raspberry Pi 4 B+ with an AMD GPU in it :)

**Comment by sidd-kishan** [comment]
https://www.jeffgeerling.com/blog/2020/external-gpus-and-raspberry-pi-compute-module-4

**Comment by FNsi** [comment]
👀
