### ISSUE TITLE
Visual corruption in DOOM Eternal 

### ISSUE THREAD

**Issue by DoomPenguin9** [GPUOpen-Drivers/AMDVLK#233]
As the title says, there are visual issues in DOOM Eternal. They occur with both AMDVLK and pro but they appear much quicker and more often with AMDVLK.  With the pro driver I can sometimes play for hours without this issue appearing but with the open driver it appears after 20-30 minutes at most. This issue does not occur with RADV.

![20210601083911_1](https://user-images.githubusercontent.com/85156713/120285401-badad880-c2ac-11eb-8500-8d8f1e159453.jpg)
![20210601083858_1](https://user-images.githubusercontent.com/85156713/120285438-c62e0400-c2ac-11eb-8208-e84e888beecd.jpg)
![20210523010936_1](https://user-images.githubusercontent.com/85156713/120285506-d47c2000-c2ac-11eb-980e-bbaed2134b95.jpg)
![20210523103551_1](https://user-images.githubusercontent.com/85156713/120285563-e362d280-c2ac-11eb-9df0-60575bc477c9.jpg)

**Comment by OdinVex** [comment]
I have the same issue, except mine also extends to many splash graphics, such as when starting any Challenge and the ripping of a heart happens.

**Comment by DoomPenguin9** [comment]
This no longer happens for me with 2024.Q1.3-1
