### ISSUE TITLE
Graphical glitches in Fifa 19 when using DX12

### ISSUE THREAD

**Issue by Ahmed-E-86** [GPUOpen-Drivers/AMDVLK#234]
Fifa 19 has graphical glitches when using DX12 as you can see in this picture:

![Screenshot from 2021-06-23 12-55-57](https://user-images.githubusercontent.com/29783425/123096510-74057c00-d42f-11eb-9104-3535c5c6b2e4.png)

It does not happen in the main menu, it happens after starting a match.

**System specifications:**
**GPU:** AMD HD 8750M 2gb vram
**Driver:** Mesa 21.1.3 - AMDVLK v-2021.Q2.5
**OS:** Linux Mint 20.1 Cinnamon
**Linux Kernel:** 5.11.0-22
vkd3d-proton 2.3.1

**Comment by jinjianrong** [comment]
The issue is not reproduced with latest driver
