### ISSUE TITLE
Deliver Us The Moon crashes during loading (DX12)

### ISSUE THREAD

**Issue by Ahmed-E-86** [GPUOpen-Drivers/AMDVLK#235]
Deliver Us The Moon crashes during loading, that happened after changing DirectX from version 11 to 12.

**System specifications:**
**GPU:** AMD HD 8750M 2gb vram
**Driver:** Mesa 21.1.3 - AMDVLK v-2021.Q2.5
**OS:** Linux Mint 20.1 Cinnamon
**Linux Kernel:** 5.11.0-22
vkd3d-proton 2.3.1

**Comment by jinjianrong** [comment]
Please try 2021.Q3.2

**Comment by Ahmed-E-86** [comment]
My GPU is not supported anymore, but good to know that it is fixed for other users of AMDVLK. Thanks anyway.
