### ISSUE TITLE
vkGetPipelineCacheData does not set pDataSize when private data size is 0

### ISSUE THREAD

**Issue by samikhawaja** [GPUOpen-Drivers/AMDVLK#237]
vkGetPipelineCacheData documentation says that the implementation should write the size of the data written in pDataSize. AMDVLK implementation only does it when privateDataSize is 0.

**Comment by jinjianrong** [comment]
@samikhawaja  will you work on the issue?

**Comment by samikhawaja** [comment]
The fix for this is already in: https://github.com/GPUOpen-Drivers/xgl/pull/119

Sorry couldn't link the issue with PR.
