### ISSUE TITLE
Prey (2017) - green screen during cut-scene "black-outs"

### ISSUE THREAD

**Issue by thomasfsteeples** [GPUOpen-Drivers/AMDVLK#241]
In the video game Prey (2017), I am experiencing this really annoying visual bug where in cut-scenes where the screen "blacks out", I instead get a screen with green lines. The HUD is preserved, and when the screen actually renders something non-trivial, it's fine.

As an example, I've attached two images from the intro - when Alex has their eyes closed, I get the green screen, but when they go to turn off their alarm clock, rendering kicks in. 

![Screenshot from 2021-07-03 13-59-35](https://user-images.githubusercontent.com/32720359/124356262-f864b580-dc0c-11eb-8925-94a7d74acc44.png)
![Screenshot from 2021-07-03 13-59-46](https://user-images.githubusercontent.com/32720359/124356263-f8fd4c00-dc0c-11eb-84f4-b0b306260d08.png)

Originally posted this to the Proton issues page for the game: https://github.com/ValveSoftware/Proton/issues/251#issuecomment-873410725. Here one of the team members asked me to use a different Vulkan implementation. Using RADV, the black screen renders as expected.

If there any way of getting the desired behaviour under AMDVLK? Any help would be greatly appreciated. Thank you for your time.

**Comment by jinjianrong** [comment]
@thomasfsteeples  the issue might have been fixed in LLPC dev branch, could you give it a try?

**Comment by jinjianrong** [comment]
Please try 2021.Q3.2 build
