### ISSUE TITLE
Anonymous user with AMDVLK organization

### ISSUE THREAD

**Issue by TheEvilSkeleton** [GPUOpen-Drivers/AMDVLK#244]
An unknown user by the name of [procedural](https://github.com/procedural) created the [AMDVLK](https://github.com/amdvlk) organization. It contains some of AMD's technologies, I think, and I'm not exactly sure what the user is trying to do with this organization.

I don't know if this is a trademark/copyright issue. I tried reporting it to GitHub but the requirement is either being the trademark holder or being authorized to act on their behalf, so I am unqualified to report it.

If a member that is qualified to report wants to report to GitHub, then here's a link to help you: https://support.github.com/contact/trademark-policy

**Comment by jinjianrong** [comment]
@TheEvilSkeleton Thanks for the information.

**Comment by TheEvilSkeleton** [comment]
No problem. If possible, keep me updated please.
