### ISSUE TITLE
VkPhysicalDeviceFloat16Int8FeaturesKHR on create physical device throws VK_ERROR_OUT_OF_HOST_MEMORY

### ISSUE THREAD

**Issue by FernandoS27** [GPUOpen-Drivers/AMDVLK#253]
It seems to be regression as this worked on the windows driver 21.8.2, I just experienced it in 21.9.1. AMDVLk users had reported before hand that it was causing a crash. It happens between 0.2.0.193 and 0.2.0.196

If you need a test example, just use the tools I provided here: https://github.com/GPUOpen-Drivers/AMDVLK/issues/251 Running any homebrew/game on yuzu, will fail creating the device due to this extension.

EDIT: only mainline 747 and older will show the bug. For the newer versions, I deactivated the extension on AMDVLK and AMD propietary after version 0.2.0.193

**Comment by Moonlacer** [comment]
I second this, happens in my testing as well

**Comment by RinMaru** [comment]
[Yuzu mainline 747](https://github.com/yuzu-emu/yuzu-mainline/releases/tag/mainline-0-747) Link so you dont have to search the Repo

**Comment by jinjianrong** [comment]
@FernandoS27 we are not allowed to run the emulator. could the issue be reproduced with the renderdoc capture in https://github.com/GPUOpen-Drivers/AMDVLK/issues/251?

**Comment by FernandoS27** [comment]
> @FernandoS27 we are not allowed to run the emulator. could the issue be reproduced with the renderdoc capture in #251?

Should be possible as I captured it before patching it.

**Comment by FernandoS27** [comment]
After rechecking. It turned out to be an issue in our side that was shadowed and didn't hppen in other drivers for some reason. 8memory coprruption).
