### ISSUE TITLE
Feature request: VK_GOOGLE_display_timing 

### ISSUE THREAD

**Issue by DanPartelly** [GPUOpen-Drivers/AMDVLK#26]
Please consider adding and supporting VK_GOOGLE_display_timing

**Comment by oscarbg** [comment]
+1
it was talked at GDC 2018 by Croteam @ 
"Advanced Graphics Techniques Tutorial: The Elusive Frame Timing: A Case for Smoothness Over Speed"
presentation and a technique using this extension can help alleviate micro-stutering and greater smoothness..

**Comment by jinjianrong** [comment]
Thanks for the information. We will add it into our work list.

**Comment by kleinerm** [comment]
Hi. Given that this is 2 years old by now, Is there any timeline for when support for VK_GOOGLE_display_timing could be expected?

Thanks.

**Comment by JacobHeAMD** [comment]
Dup with https://github.com/GPUOpen-Drivers/AMDVLK/issues/31
