### ISSUE TITLE
Splitgate corruption and crash

### ISSUE THREAD

**Issue by adamfmatt** [GPUOpen-Drivers/AMDVLK#260]
Splitgate https://store.steampowered.com/app/677620/Splitgate/ suffers from heavy corruption issues on Main Menu and the maps particularly Oasis and Club Silo.

It will also crash inconsistently when using the portal mechanic. The attached crash callstack was generated precisely when two portals were opened and the viewport was rendered. This crash also happens with Mesa RADV and has been reported.

- OS: Debian GNU/Linux 11 (bullseye) x86_64
- Kernel: 5.10.0-9-amd64
- CPU: AMD Ryzen 5 2400G (8) @ 3.400GHz
- GPU: AMD ATI Radeon Vega Series / Radeon Vega Mobile Series
- Driver: amdvlk_2021.Q4.1
 
[sp-amdvlk-crash.txt](https://github.com/GPUOpen-Drivers/AMDVLK/files/7611771/sp-amdvlk-crash.txt)

![splitgate-corrupt1](https://user-images.githubusercontent.com/48870188/143683097-c146dbf1-f30a-4907-baf3-bbb346d52abf.jpg)

![Silo-corrupt1](https://user-images.githubusercontent.com/48870188/143683118-c0e27df4-f64d-4c56-a47d-4cc472b2f626.jpg)

![Oasis-corrupt1](https://user-images.githubusercontent.com/48870188/143683123-fe8e64f0-7ee7-470e-b99f-c944df52eadf.jpg)

**Comment by jinjianrong** [comment]
Not driver issue
