### ISSUE TITLE
Unsupported image format with Frostbite engine on GRVK

### ISSUE THREAD

**Issue by libcg** [GPUOpen-Drivers/AMDVLK#264]
Battlefield 4 and Plants vs Zombies on [GRVK](https://github.com/libcg/grvk) (Mantle API) try to create an image with the following properties:
- VkFormat: `VK_FORMAT_R8G8B8A8_UNORM`
- VkImageType: `VK_IMAGE_TYPE_3D`
- VkImageTiling: `VK_IMAGE_TILING_LINEAR`
- VkImageUsageFlags: `VK_IMAGE_USAGE_TRANSFER_SRC_BIT | VK_IMAGE_USAGE_TRANSFER_DST_BIT | VK_IMAGE_USAGE_SAMPLED_BIT`
- VkImageCreateFlags: `0`

`vkGetPhysicalDeviceImageFormatProperties` returns `VK_ERROR_FORMAT_NOT_SUPPORTED` for this combination, ultimately causing graphical glitches. Reproduced on Adrenalin 21.11.3 (Vulkan driver 2.0.204) with a 5700 XT. RADV doesn't have this issue.

**Comment by qiaojbao** [comment]
Current driver has supported this format.
Test with Navi10.
{maxExtent = {width = 16384, height = 16384, depth = 8192}, maxMipLevels = 15, maxArrayLayers = 1, sampleCounts = 1, maxResourceSize = 2454267028}
