### ISSUE TITLE
Rendering issue in Battlefield 1 due to anisotropic filtering for single level images

### ISSUE THREAD

**Issue by ms178** [GPUOpen-Drivers/AMDVLK#267]
RADV and AMDVLK both now make use of anisotropic filtering for single level images according to a Mesa developer, leading to very noticeable texture rendering issue in Battlefield 1. I first reported this issue to Mesa right after their implementation landed in Mesa-git (see https://gitlab.freedesktop.org/mesa/mesa/-/issues/5753 with more screenshots and the comment from the Mesa dev), but during testing I found that AMDVLK is also affected. I tried DX11 and DX12 (via DXVK and VKD3D-Proton), both render pathes show the issue.

The Mesa dev thinks it is a bug of the game and works on a workaround. I hope it can also be worked around in AMDVLK.

![Screenshot_20211216_165734](https://user-images.githubusercontent.com/19559105/148462441-44397ad3-9b5d-4278-8b47-12d16b6b95e5.png)

My GPU is a Vega 56.
Tested with AMDVLK v-2021.Q4.3

**Comment by ms178** [comment]
This still reproduces with the current AMDVLK. Is there an ETA for a fix?

**Comment by WenqingLiAMD** [comment]
> This still reproduces with the current AMDVLK. Is there an ETA for a fix?

Could you help verify it with AMDVLK v-2022.Q4.2?

**Comment by ms178** [comment]
@WenqingLiAMD I'd love to test that, but Battlefield 1 is broken right now on Linux due to an incompatibility between the new EA web app and Proton. Nevertheless, as the new AMDVLK release notes mentioned a fixed rendering issue in Battlefield 1, I thought that it meant this issue, but I will check that to make sure, once the mentioned issue with the EA web app is resolved.
