### ISSUE TITLE
AMD_VULKAN_ICD=amdvlk-pro not working anymore

### ISSUE THREAD

**Issue by CosmicFusion** [GPUOpen-Drivers/AMDVLK#269]
In my previous linux installations i was able to use the environment variable  AMD_VULKAN_ICD to switch between vulkan layers but now when choosing amdvlk-pro i get greeted the the Open source amdvlk instead
[Right Now](https://github.com/GPUOpen-Drivers/AMDVLK/files/7862860/after.txt)

[Before](https://github.com/GPUOpen-Drivers/AMDVLK/files/7862861/before.txt)

**Comment by qiaojbao** [comment]
According to README:
If RADV is also installed in the system, AMDVLK driver will be enabled by default after installation. You can switch the driver between AMDVLK and RADV by environment variable AMD_VULKAN_ICD = AMDVLK or RADV.

The AMDVLK and amdvlk-pro all use the same json file location, so I guess you installed AMDVLK deb package and then json file driver location was changed to AMDVLK open.
