### ISSUE TITLE
Vulkan 1.3?

### ISSUE THREAD

**Issue by oscarbg** [GPUOpen-Drivers/AMDVLK#271]

**Comment by Flakebi** [comment]
https://github.com/GPUOpen-Drivers/AMDVLK/releases/tag/v-2022.Q1.2

**Comment by oscarbg** [comment]
thanks and sorry for opening two issues..

**Comment by oscarbg** [comment]
any clue on AMD Windows drivers.. supposedly a beta release was made yesterday according to khronos Vulkan 1.3 press release..

**Comment by Flakebi** [comment]
No problem.
The windows driver is available here: https://www.amd.com/en/support/kb/release-notes/rn-rad-win-22-1-2-vulkan-1-3 (download link is in the middle of the page)

**Comment by oscarbg** [comment]
nice, thanks! I couldn’t find anywhere..
