### ISSUE TITLE
Request to provide precompiled builds at http://repo.radeon.com/amdvlk/ soon?

### ISSUE THREAD

**Issue by oscarbg** [GPUOpen-Drivers/AMDVLK#28]
Hi,
just exploring ROCM repo "repo.radeon.com" found and amdvlk folder..
altough is empty right now, that is a hint that precompiled builds are coming soon there?
for ex. builds for Ubuntu (similar to ROCM) are going to be provided soon?
thanks..

**Comment by jinjianrong** [comment]
yes, we are going to provide builds on repo.radeon.com

**Comment by oscarbg** [comment]
seems they are live!
I hope every weekly drop or so of code gets a new build on the repo!
thanks &closing..

**Comment by JacobHeAMD** [comment]
Please hold on, the repo doesn't work yet because I was interrupted by other urgent issue. Will keep you posted once it works.

**Comment by JacobHeAMD** [comment]
It's supposed to be working now, please try it. 
wget -qO - http://repo.radeon.com/amdvlk/apt/debian/amdvlk.gpg.key | sudo apt-key add -
sudo sh -c 'echo deb [arch=amd64] http://repo.radeon.com/rocm/apt/debian/ xenial main > /etc/apt/sources.list.d/amdvlk.list'
apt update
apt-get install amdvlk

**Comment by nadrolinux** [comment]
Hello,
Have you got any plans to update this repository?
Patryk,

**Comment by JacobHeAMD** [comment]
Sorry, it is in "pending" status. Hopefully I'll have time on this this week.

**Comment by ernstp** [comment]
Ping for v2018.4.1 ?

**Comment by ernstp** [comment]
Right, so why not add them to the repository at http://repo.radeon.com/amdvlk/apt/debian/pool/main/a/amdvlk/ also? So people can start using that...

**Comment by CrackedCrafterz** [comment]
Hello @JacobHeAMD 

I regularly build arch packages (.pkg.tar.xz) from amdvlk. Would be possible if someone would view [this](https://github.com/CrackedCrafterz/AMDVLK-Arch) ?, maybe it would then enlarge the pool and nobody needs to waste over 2 hours on building 😃

**Comment by JacobHeAMD** [comment]
The source for Ubuntu 18.04 is deployed to repo.radeon.com, please try it.
sudo wget -qO - http://repo.radeon.com/amdvlk/apt/debian/amdvlk.gpg.key | sudo apt-key add -
sudo sh -c 'echo deb [arch=amd64] http://repo.radeon.com/amdvlk/apt/debian/ bionic main > /etc/apt/sources.list.d/amdvlk.list'
apt update
apt-get install amdvlk

**Comment by ernstp** [comment]
That works fine... 32-bit libraries? Not 32-bit Ubuntu support of course, just the multilib stuff...

**Comment by JaxLinAMD** [comment]
32bit pakcage is provided since v-2020.Q3.1
