### ISSUE TITLE
OpenXR crash in the AMDVLK DLL on the current master branch of Godot

### ISSUE THREAD

**Issue by marc-weber1** [GPUOpen-Drivers/AMDVLK#281]
Not sure how reproducible this is on other AMD GPUs or other VR headsets, but on an RX 580 and any Oculus headset and the latest drivers, trying to use OpenXR with godot results in a crash in a call to free a vector of RID:

[Godot Issue](https://github.com/godotengine/godot/issues/62231)

If you compile godot with debug symbols and run it with steamVR connected and open the given project with an AMD GPU, this issue should happen consistently. If it doesn't, it may be an oculus, godot, or GPU specific issue. If it isn't, though, there may be a much more easy way of reproducing the issue without using Godot at all.

If it seems like a godot-specific issue, feel free to close the issue. Thanks

**Comment by jinjianrong** [comment]
we can reproduce this issue on other vendor's card, it’s most likely an app-side issue
