### ISSUE TITLE
Request: support VK_NV_compute_shader_derivatives for VKD3D shader model 6.6 support

### ISSUE THREAD

**Issue by oscarbg** [GPUOpen-Drivers/AMDVLK#289]
Hi,

this extension is supported by Nvidia on recent GPUs and also on Mesa AMD RADV driver and Intel ANVIL driver..
it's required by VKD3D for exposing SM6.6 support:
https://github.com/HansKristian-Work/vkd3d-proton/blob/7160ee223a1966228ea925eb906517e5e542872d/libs/vkd3d/device.c#L6248
and it may be needed for running UE5 projects using nanite using VKD3D.. see:
https://github.com/HansKristian-Work/vkd3d-proton/issues/678#issuecomment-1080765645

thanks..

**Comment by oscarbg** [comment]
note hope this is enabled also AMD Windows Vulkan driver..

**Comment by oscarbg** [comment]
note latest Intel Windows driver 3729 includes it at least for Intel Xe and higher..

**Comment by oscarbg** [comment]
Any update? Has work begun?

**Comment by ruiminzhao** [comment]
This extension has already been delivered in commit-id: 97a755f58b7820c79d2f6315089fb70dd43df6a0
That means the binary after Feb can be used for this extension.
Thanks.

**Comment by oscarbg** [comment]
Hi @ruiminzhao,
thanks for answering.. 
but seems still the extension not shipping in latest 2023q2.2 since I search for the extension and is missing everywhere:
1) this 6900xt vulkan.gpuinfo report using "2023.Q2.2 (LLPC)" driver doesn't show "VK_NV_compute_shader_derivatives" extension:
http://vulkan.gpuinfo.org/displayreport.php?id=21219#extensions
2) searching "VK_NV_compute_shader_derivatives" string is missing in amdvlk.so from amdvlk_2023.Q2.2_amd64 package..
3) searching in both:
https://github.com/GPUOpen-Drivers/xgl/blob/dev/icd/api/strings/extensions.txt
https://github.com/GPUOpen-Drivers/xgl/blob/dev/icd/api/include/vk_extensions.h
VK_NV_compute_shader_derivatives is missing..
so sorry for reasking but are you sure extension has been shipped in amdvlk repo?
thanks..

**Comment by ruiminzhao** [comment]
@oscarbg After a further check and syncing, it can be confirmed this extension has been implemented. But it still need some further tests here. Whether to deliver this NV extension, it will be decided by our project manager. Thanks.

**Comment by oscarbg** [comment]
thanks @ruiminzhao, hope if not delivering this NV ext, it's because a KHR or EXT extension is being developed like for mesh shader..

**Comment by jinjianrong** [comment]
The extension is enabled for vkd3d in v-2023.Q4.3
