### ISSUE TITLE
New Rise of the Tomb Raider Linux game doesn't work with AMDVLK..

### ISSUE THREAD

**Issue by oscarbg** [GPUOpen-Drivers/AMDVLK#29]
please see:
https://www.phoronix.com/scan.php?page=news_item&px=AMDVLK-Rise-of-the-Tomb-Raider

> Sometimes I would get a run to pass with low quality settings at 1080p, but within a few runs, the driver would hang. The AMDVLK hanging would almost always occur within the "Geothermal Valley" scene of the Rise of the Tomb Raider run. 

> AMDVLK as of right now doesn't seem to work properly with Rise of the Tomb Raider with the Polaris, Fiji, and Vega hardware I tested

**Comment by jinjianrong** [comment]
@oscarbg @michaellarabel   we had a hot fix to workaround the hang issue, could you give it a try?
