### ISSUE TITLE
Release 2022.Q3.4 fails to compile due to missing header

### ISSUE THREAD

**Issue by v-fox** [GPUOpen-Drivers/AMDVLK#293]
Tried [updating to 2022.Q3.4](https://build.opensuse.org/package/show/home:X0F:HSF/amdvlk) but got:
```
[ 9998s] /home/abuild/rpmbuild/BUILD/amdvlk-2022.Q3.4/gpurt/src/gpurtDevice.cpp:56:10: fatal error: 'pipelines/g_internal_shaders.h' file not found
[ 9998s] /home/abuild/rpmbuild/BUILD/amdvlk-2022.Q3.4/gpurt/src/gpurtInternalShaders.cpp:31:10: fatal error: 'pipelines/g_internal_shaders.h' file not found
```

**Comment by jinjianrong** [comment]
please refer to the readme: https://github.com/GPUOpen-Drivers/AMDVLK/tree/master#install-shader-compiler-tools

**Comment by v-fox** [comment]
> Hi, 2022.Q3.4 added two new dependencies for the gpurt library.
The [DirectXShaderCompiler](https://github.com/microsoft/DirectXShaderCompiler) and [glslang](https://github.com/KhronosGroup/glslang) are needed:

Thanks for clearing that up. But if those are hard dependencies then build should fail immediately on configuration instead of 3 hours into compilation. It should do its own search for dependencies, that's what cmake is for.

**Comment by RarogCmex** [comment]
I am avoiding that bug by implementing raytracing USE flag in ebuild. See https://wiki.gentoo.org/wiki/AMDVLK#Raytracing_support_and_DXC and https://gitweb.gentoo.org/repo/proj/guru.git/commit/?h=dev&id=26c0cadb6e243d8fdf6aaaa6262727c127ebcd44

**Comment by RarogCmex** [comment]
-DVKI_RAY_TRACING=$(usex raytracing)

**Comment by v-fox** [comment]
> -DVKI_RAY_TRACING=$(usex raytracing)

Thanks for this pointer. After I achieved stability with Mesa, I gave up on amdvlk. But disabling this for 32-bit builds only to let them compile to be packaged as potential fallback is a good idea.
