### ISSUE TITLE
Unknown AMD GPU

### ISSUE THREAD

**Issue by redni** [GPUOpen-Drivers/AMDVLK#30]
**Arch Linux**
**AMDVLK commit 29**

`$ vulkaninfo`

```sh
	apiVersion     = 0x401046  (1.1.70)
	driverVersion  = 8388637 (0x80001d)
	vendorID       = 0x1002
	deviceID       = 0x9851
	deviceType     = INTEGRATED_GPU
	deviceName     = Unknown AMD GPU
```
And every VK_LAYER ...

`GPU id       : 0 (Unknown AMD GPU)`

On vulkan-radeon work fine and system show `AMD RADV MULLINS (LLVM 6.0.0)`, problem is only with AMDVLK.

**Comment by JacobHeAMD** [comment]
Not like Radv setting the deviceName according to the device ID by itself, AMDVLK gets the deviceName by libdrm interface, amdgpu_get_marketing_name, which gets it from amdgpu.ids. 
You can workaround it by adding one line to /usr/share/libdrm/amdgpu.ids.
