### ISSUE TITLE
 vkd3d-proton test uav_counter_null_behavior_dxil GPU hang

### ISSUE THREAD

**Issue by mbriar** [GPUOpen-Drivers/AMDVLK#300]
The [vkd3d-proton](https://github.com/HansKristian-Work/vkd3d-proton) `uav_counter_null_behavior_dxil` test hangs the GPU on AMDVLK.  
To reproduce build and run the vkd3d-proton tests:  
```
git clone --recurse-submodules https://github.com/HansKristian-Work/vkd3d-proton
mkdir vkd3d-proton/build && cd vkd3d-proton/build
meson .. -Denable_tests=true
ninja
VKD3D_TEST_FILTER=uav_counter_null_behavior_dxil ./tests/d3d12
```

The test also hangs on amdgpu-pro 22.20, but passes on RADV.
  
GPU 6700XT/NAVI22
AMDVLK v-2022.Q3.5
vkd3d-proton commit 212ae62b5
  
(excuse me for spamming all these issues, which for all i know could also be vkd3d-proton bugs, but I'm somewhat interested in seeing AMDVLK work better with vkd3d-proton games.)

**Comment by jinjianrong** [comment]
The issue is fixed new release
