### ISSUE TITLE
Expose VK_EXT_attachment_feedback_loop_layout

### ISSUE THREAD

**Issue by Joshua-Ashton** [GPUOpen-Drivers/AMDVLK#303]
Trivial to implement.

Would be nice to stop users making bug reports on DXVK because of the lack of this EXT.

ref: https://github.com/doitsujin/dxvk/issues/1862

**Comment by Blisto91** [comment]
Can be closed as of 2023.Q1.1 https://github.com/GPUOpen-Drivers/AMDVLK/releases/tag/v-2023.Q1.1
