### ISSUE TITLE
Missing VK_EXT_image_drm_format_modifier

### ISSUE THREAD

**Issue by nyanmisaka** [GPUOpen-Drivers/AMDVLK#317]
`vulkan: physical device does not support DRM format modifiers`

[VK_EXT_image_drm_format_modifier](https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/VK_EXT_image_drm_format_modifier.html) is required for importing image from dma buf that contains modifiers.

NV proprietary, Intel ANV and RADV have supported this for a while.

Since these two related extensions have been supported in AMDVLK, it'd be great if we can have modifier support.
- VK_EXT_external_memory_dma_buf 
- VK_KHR_external_memory_fd

Thanks!

**Comment by jinjianrong** [comment]
We have been working on the extension.

**Comment by nyanmisaka** [comment]
@jinjianrong Nice to hear that! Any plans on adding modifier in KMD for gfx8 Polaris? This generation still has a wide user base, but due to the big difference from gfx9, developers from Google only added modifier support for gfx9+.

- https://patchwork.freedesktop.org/patch/247020/
- https://patchwork.freedesktop.org/series/80262/
- https://gitlab.freedesktop.org/mesa/mesa/-/issues/5882

**Comment by nyanmisaka** [comment]
This can be closed by https://github.com/GPUOpen-Drivers/AMDVLK/releases/tag/v-2023.Q3.1
