### ISSUE TITLE
[llpc] amdvlk-2023.Q1.3 build is failing 

### ISSUE THREAD

**Issue by shivania2** [GPUOpen-Drivers/AMDVLK#319]
I am trying to build amdvlk-2023.Q1.3 and getting following error during build

FAILED: compiler/llpc/llvm/tools/lgc/interface/lgc/LgcDialect.h.inc 
cd /usr/src/photon/BUILD/amdvlk-2023.Q1.3/x86_64-vmware-linux && /usr/src/photon/BUILD/amdvlk-2023.Q1.3/x86_64-vmware-linux/compiler/llpc/llvm/bin/llvm-dialects-tblgen -gen-dialect-decls --dialect lgc -I /usr/src/photon/BUILD/amdvlk-2023.Q1.3/llpc/lgc -I/usr/src/photon/BUILD/amdvlk-2023.Q1.3/x86_64-vmware-linux/compiler/llpc/llvm/include -I/usr/src/photon/BUILD/amdvlk-2023.Q1.3/llvm-project/llvm/include -I/usr/src/photon/BUILD/amdvlk-2023.Q1.3/llpc/lgc/../imported/llvm-dialects/include /usr/src/photon/BUILD/amdvlk-2023.Q1.3/llpc/lgc/interface/lgc/LgcDialect.td --write-if-changed -o compiler/llpc/llvm/tools/lgc/interface/lgc/LgcDialect.h.inc -d compiler/llpc/llvm/tools/lgc/interface/lgc/LgcDialect.h.inc.d
/usr/src/photon/BUILD/amdvlk-2023.Q1.3/llpc/lgc/interface/lgc/LgcDialect.td:33:21: error: Couldn't find class 'PointerType'
def BufferPointer : PointerType<7>;

Build command
``` 
      cmake -GNinja -S xgl -DLLVM_PARALLEL_LINK_JOBS=1 -DVKI_RAY_TRACING=OFF  -B builds/Release64
      cmake --build builds/Release64
```

**Comment by WenqingLiAMD** [comment]
could you check if the llpc's submodule llvm-dialects is up-to-date?

**Comment by shivania2** [comment]
Thanks.
