### ISSUE TITLE
Writing to MRT with masked color write fails

### ISSUE THREAD

**Issue by Themaister** [GPUOpen-Drivers/AMDVLK#32]
MRT with 4 RTs, and color write mask setup:
0: 0x0
1: 0xf
2: 0xf
3: 0xf

The driver is confused and RT 1 outputs are written to RT 0, and so on, off-by-one.

**Comment by amdrexu** [comment]
Could you attache the shader please? So we can have a check.

**Comment by Themaister** [comment]
[fossilize.json.txt](https://github.com/GPUOpen-Drivers/AMDVLK/files/1991974/fossilize.json.txt)
[gbuffer.asm.txt](https://github.com/GPUOpen-Drivers/AMDVLK/files/1991976/gbuffer.asm.txt)

To replay the pipeline creation with all info:
```
git clone git://github.com/Themaister/Fossilize
cd Fossilize
git submodule update --init
mkdir build
cd build
cmake ..
make -j16
./cli/fossilize-replay /tmp/fossilize.json.txt --filter-graphics 1
```

**Comment by amdrexu** [comment]
Reproduced. We will have a look and give you update once the root cause is pinpointed. Thank you.

**Comment by amdrexu** [comment]
We have found the root cause and fix it internally. Will be available in next code base update. Thank you.

**Comment by Themaister** [comment]
Pulled latest driver and seems to work fine now.
