### ISSUE TITLE
Visual corruption with water effect in Doom Eternal raytracing

### ISSUE THREAD

**Issue by aufkrawall** [GPUOpen-Drivers/AMDVLK#325]
First open area in first level:

RT on:
![782330_20230609185919_1](https://github.com/GPUOpen-Drivers/AMDVLK/assets/13510490/e53c92b2-77d9-4a13-bde2-85b709d9611b)

RT off:
![782330_20230609185955_1](https://github.com/GPUOpen-Drivers/AMDVLK/assets/13510490/e5e1f30b-a319-4b95-8f1a-9e989508a5ca)

amdvlk 2023.Q2.2-1, RX 6700 XT, 1440p, maximal visuals

**Comment by bluestang2006** [comment]
What version of Proton are you using? The only working version for me is Proton 7...
Any version of Proton 8 asserts and refuses the launch the game.

**Comment by bluestang2006** [comment]
> First open area in first level:
> 
> RT on: ![782330_20230609185919_1](https://user-images.githubusercontent.com/13510490/244757794-e53c92b2-77d9-4a13-bde2-85b709d9611b.png)
> 
> RT off: ![782330_20230609185955_1](https://user-images.githubusercontent.com/13510490/244757834-e5e1f30b-a319-4b95-8f1a-9e989508a5ca.png)
> 
> amdvlk 2023.Q2.2-1, RX 6700 XT, 1440p, maximal visuals

Looks this has been fixed, I built the dev branch this morning and observed that the water appears correct in the first level.
Keep an eye out for a new release, it should be appearing soon.
