### ISSUE TITLE
Assassins Creed Origins White lines

### ISSUE THREAD

**Issue by Blisto91** [GPUOpen-Drivers/AMDVLK#328]
Original dxvk issue reported with the Windows driver instead: https://github.com/doitsujin/dxvk/issues/3545

When using amdvlk together with dxvk in Assassins Creed Origins in some scenes, like the present day cave scene after prologue, along the edges of objects a white line can appear at certain angles. This does not happen with radv.

<details>
  <summary>Example screenshot</summary>
  
![Screenshot_20230704_182307](https://github.com/GPUOpen-Drivers/AMDVLK/assets/47954800/4739b089-7d30-49bf-aa2c-bbd317b96420)
</details>

GPU: 7900XTX
Driver version: 2023Q2.3
dxvk version: 2.2 and current master

apitrace with the issue. When i get out of the cave and look inside again the white lines can be seen at the ceiling at certain angles.
https://drive.proton.me/urls/08D98GNA6M#ZZSKXmDXVS1U

**Comment by CME42** [comment]
This seems to be related to trunc_coord/truncateCoords, radv disables trunc_coord for textureGather/tg4. I can't repro it anymore with amdvlk when I disable truncateCoords.

There also seems to be a fix for gfx11 with TA_CNTL2.TRUNCATE_COORD_MODE which I can't find in amdvlk: https://gitlab.freedesktop.org/mesa/mesa/-/commit/df6380ddc9c88b37355cb85d2f37697192354aaa

**Comment by Blisto91** [comment]
Thanks can confirm it is fixed with 2023.Q3.3
