### ISSUE TITLE
`SPV_KHR_cooperative_matrix` support

### ISSUE THREAD

**Issue by masahi** [GPUOpen-Drivers/AMDVLK#336]
Is there a plan to support this extension? This is going to be very useful for deep learning workload. 

I heard that it is already supported by the closed-source driver.

**Comment by oscarbg** [comment]
Rdna3 only seems anyway..

**Comment by amdrexu** [comment]
It might be released in the near future. We are doing some clean-up work.

**Comment by jinjianrong** [comment]
Done in v-2023.Q4.2 release
