### ISSUE TITLE
Apt repository `repo.radeon.com/amdvlk` is out of date (8 releases obsolete)

### ISSUE THREAD

**Issue by illwieckz** [GPUOpen-Drivers/AMDVLK#340]
Hi, in http://repo.radeon.com/amdvlk/apt/debian/pool/main/a/amdvlk/ Apt repository,
the downloadable package is: `amdvlk_2023.Q1.3_amd64.deb`, from March of 2023.

But at the time I open this issue, 7 releases have been published since March of 2023.
At the time I open this issue the current release is `amdvlk_2023.Q4.1_amd64.deb`.

**Comment by illwieckz** [comment]
Is there a will to fix this issue? Or is that repository deprecated? The package on the repository is now 8 releases obsolete.

**Comment by jinjianrong** [comment]
Thanks for reporting the issue. We run into some IT issue with the repository  server. Trying to fix it.

**Comment by jinjianrong** [comment]
2023.Q4.2 is now available on the Apt repository. Please let us know if there is still problem to install it.
