### ISSUE TITLE
Artifacts with The Coffin Of Andy And Leyley

### ISSUE THREAD

**Issue by nonetrix** [GPUOpen-Drivers/AMDVLK#353]
I installed AMDVLK on my system just to have another driver just if RADV didn't work well for whatever reason, however, I didn't know at the time my system seemingly preferred running with AMDVLK by default. And ran into strange artifacts in The Coffin Of Andy And Leyley which at the time I didn't know was actually the AMDVLK drivers fault, and made [issue](https://github.com/ValveSoftware/Proton/issues/7502) at the Proton repo. As seen in the following screenshots the game becomes distorted when running with AMDVLK and menus are broken

## AMDVLK:
![2024-02-15-162324_hyprshot](https://github.com/GPUOpen-Drivers/AMDVLK/assets/45698918/d0381ec1-d8a4-44f9-ab2a-66e06537d151)
![20240217_13h40m17s_grim](https://github.com/GPUOpen-Drivers/AMDVLK/assets/45698918/498fb856-951f-42c2-8e51-be33d521b16b)
![20240217_13h38m08s_grim](https://github.com/GPUOpen-Drivers/AMDVLK/assets/45698918/5615a110-eacf-497b-812d-2c29b82d02d2)

## RADV:
![20240217_14h14m51s_grim](https://github.com/GPUOpen-Drivers/AMDVLK/assets/45698918/9bd9ead7-8d58-4442-8fd2-1a885d7bc4b4)
![20240217_14h14m59s_grim](https://github.com/GPUOpen-Drivers/AMDVLK/assets/45698918/f6d3083e-efc6-4b9c-9040-59910c150943)
![20240217_14h15m09s_grim](https://github.com/GPUOpen-Drivers/AMDVLK/assets/45698918/82fb6098-aa1f-4419-84e8-3d730d7f9964)

More information can be found on the issue I mentioned

**Comment by jinjianrong** [comment]
The issue is no more reproducible with 2024.Q3.1
