### ISSUE TITLE
Corruption with Nanite foliage and shadows in The Talos Principle 2

### ISSUE THREAD

**Issue by aufkrawall** [GPUOpen-Drivers/AMDVLK#354]
There is flickering corruption going on with foliage and shadows in The Talos Principle 2. Should be instantly noticeable after loading the first level and walking around a bit:

![835960_20240223152303_1](https://github.com/GPUOpen-Drivers/AMDVLK/assets/13510490/d52a2e46-19a1-4ce5-8606-02e3fe40dcc5)

This is probably related to Nanite (which can't be toggled in that game), but just guessing.

amdvlk [v-2024.Q1.2](https://github.com/GPUOpen-Drivers/AMDVLK/releases/tag/v-2024.Q1.2)
Radeon RX 7800 XT
Proton Experimental
selected in-game settings don't seem to matter

**Comment by jinjianrong** [comment]
Not reproduced with 2024.Q2.1 release

**Comment by aufkrawall** [comment]
It is even more broken than before, in a very obvious manner:
![835960_20240517041658_1](https://github.com/GPUOpen-Drivers/AMDVLK/assets/13510490/794f4b80-3e16-436f-a386-2669168ba2ca)

**Comment by jinjianrong** [comment]
The new issue is a regression. This is fixed 2024.Q2.2 release

**Comment by aufkrawall** [comment]
Well, yes, indeed the foliage looks fixed now. But big level geometry parts are still broken with 2024.Q2.2 on the 7800 XT:
![835960_20240605174134_1](https://github.com/GPUOpen-Drivers/AMDVLK/assets/13510490/b525a4cb-8eac-4e0f-b4c4-fc025a808c53)
