### ISSUE TITLE
DRM version is lower than the version supported by this driver

### ISSUE THREAD

**Issue by Cry-Mory** [GPUOpen-Drivers/AMDVLK#36]
I have Linux 16.4.3 with an AMD Fire Pro W9100 GPU. After compiling and copying all the driver files, running vulkan applications triggers the following error:

amdgpu_device_initialize: DRM version is 2.50.0 but this driver is only compatible with 3.x.x.
Could not create Vulkan instance : 
ERROR_INCOMPATIBLE_DRIVER

**Comment by JacobHeAMD** [comment]
Another possibility is amdgpu.ko is not modprobed, please blacklist radeon and make sure amdgpu.ko is modprobed.
