### ISSUE TITLE
Counter-Strike 2 Texture issues on skins

### ISSUE THREAD

**Issue by pyanmcbride** [GPUOpen-Drivers/AMDVLK#365]
Counter Strike 2's skins show as complety black and shiny. All other textures that aren't skins appear fine.

Refer to this issue on Valve's repo: ValveSoftware/csgo-osx-linux#3752

I don't know enough to say whether its the game or the driver causing the issue, but if anyone wants any tests done or logs let me know.

**Comment by jinjianrong** [comment]
This is an app issue. The issue is not seen with latest game release.
