### ISSUE TITLE
Vulkan SC support?

### ISSUE THREAD

**Issue by oscarbg** [GPUOpen-Drivers/AMDVLK#372]
Hi,
Nvidia latest r560 support vulkan sc development on geforce rtx consumer cards.. they ship also a vulkan sc sdk with prebuilt binaries and r560 drivers ship a tool nvidia-ppc which allows offline compilation of pipeline binaries needed in vulkan sc i believe.. is amd planning to ship support for vulkan sc in amdvlk drivers even if only for development of vulkan sc apps?

thanks..

**Comment by Degerz** [comment]
https://coreavi.com/wp-content/uploads/CoreAVI_ProductBrief_E9171_Support.pdf

Official Vulkan SC support for AMD HW is only [provided](https://www.khronos.org/conformance/adopters/conformant-products/vulkansc#submission_9) by their partner, CoreAVI ...

**Comment by jinjianrong** [comment]
Currently there is no plan to support vulkan sc in amdvlk drivers
