### ISSUE TITLE
ERROR:             loader_scanned_icd_add: Attempt to retrieve either 'vkGetInstanceProcAddr' or 'vk_icdGetInstanceProcAddr' from ICD /usr/lib/x86_64-linux-gnu/amdvlk64.so failed

### ISSUE THREAD

**Issue by 82157402** [GPUOpen-Drivers/AMDVLK#385]
OS :Ubunt 22.04
![image](https://github.com/user-attachments/assets/731d53c0-f911-4c6d-848d-04b3b938769e)

Build CMD
1)cmake -G Ninja -S xgl -B builds/Release64 -DCMAKE_C_FLAGS="-fno-lto" -DCMAKE_CXX_FLAGS="-fno-lto"
2)cmake --build builds/Release64

![image](https://github.com/user-attachments/assets/5eb05894-870f-4875-b9cf-38d300564d4a)

"vk_icdGetInstanceProcAddrSG" is not setted to the export function.
Why ?

**Comment by 82157402** [comment]
[vulkaninfo_result_enable_VK_LOADER_DEBUG.txt](https://github.com/user-attachments/files/18074688/vulkaninfo_result_enable_VK_LOADER_DEBUG.txt)

![image](https://github.com/user-attachments/assets/c8550054-b8cc-46bf-b450-2774b8a32ea2)

**Comment by qiaojbao** [comment]
could you try  -DVKI_ENABLE_LTO=OFF cmake option?

**Comment by 82157402** [comment]
cmake -G Ninja -S xgl -B builds/Debug64  -DCMAKE_BUILD_TYPE=Debug -DLLVM_PARALLEL_LINK_JOBS=2  -DVKI_ENABLE_LTO=OFF
I try Debug Version , it is running.
