### ISSUE TITLE
Reversed Z-buffer not working

### ISSUE THREAD

**Issue by mikedilger** [GPUOpen-Drivers/AMDVLK#4]
This was on ArchLInux, with an R7 360.  I haven't tried other cards or OS builds.

Using the latest code from the amdvlk-git AUR repo for ArchLinux.

I have tried other drivers (vulkan-radeon) where my code works fine.

I would provide code but its in rust and might not be your cup of tea.  The code is very straightfoward, two piercing triangles.  In reversing the z-buffer, the following changes were flipped from 1.0 to 0.0 or the opposite:   viewport min_depth and max_depth;  clear value; depth_compare_op.  LunarG validation reports no issues.

Oh, I also get a SIGSEGV on exit (gdb seems to think it is in libpthread) which doesn't happen with the other drivers.

**Comment by procedural** [comment]
I think it would be helpful if you could compile a minimal repro executable in Rust with debug symbols enabled and share it here...

**Comment by mikedilger** [comment]
I've stripped out everything easy to strip out.  Without rewriting it carefully to be minimal, it is still 41MB.

I am on a different machine today with a different graphics card vendor, so I can't verify that this doesn't work on the AMD card, but I will check later today (if the power is restored to my home).

[siege-client.gz](https://github.com/GPUOpen-Drivers/AMDVLK/files/1604666/siege-client.gz)

**Comment by procedural** [comment]
Is this what I should see?

![screenshot from 2018-01-05 18-55-05](https://user-images.githubusercontent.com/28234322/34616669-ffb64534-f249-11e7-8c52-eaef2c4938ce.png)

A desired result would be the white triangle on top?

**Comment by procedural** [comment]
![screenshot from 2018-01-05 19-05-30](https://user-images.githubusercontent.com/28234322/34617262-e950bd04-f24b-11e7-8164-762426c3a59e.png)

Crash happens after this instruction, check line `154` of `main.rs`, would be nice if you could share the source code too, if you can.

**Comment by procedural** [comment]
Vulkan trace calls of the application, if they can be helpful: https://pastebin.com/raw/KVUeTTyB

**Comment by procedural** [comment]
I see no vkCmdSetViewport calls in the trace log...

**Comment by procedural** [comment]
I guess viewport information is passed with `vkCreateGraphicsPipelines`...

**Comment by procedural** [comment]
Trace file generated from `vktrace` compiled from https://github.com/LunarG/VulkanTools/commit/6620d66, if someone wants to debug it outside of Linux (if it's portable enough): https://mega.nz/#!YcZXWCjK!7ZNOMARxGeAaD46kzlvk25DWb4cSdsWYjzWm9wM9rW8

**Comment by procedural** [comment]
Ok, so your application calls `vkCreateGraphicsPipelines` two times which both set `minDepth` to `1` and `maxDepth` to `0`...

![screenshot from 2018-01-05 21-34-40](https://user-images.githubusercontent.com/28234322/34622993-7c3ead24-f260-11e7-854b-b28ba48fd99d.png)

**Comment by mikedilger** [comment]
It's not efficient of me to call vkCreateGraphicsPipelines multiple times, but that should be ok.

min_depth to 1 and max_depth to 0 is what I intend, that's the reversed z-buffer. Clear value is 0 (max depth) and compare_op is greater_or_equal. It should behave very similar to a normal z-buffer configuration, except to give better floating point resolution at the far plane (since that is nearer to 0.0)

source code:
[siege-client-amdvlk.tar.gz](https://github.com/GPUOpen-Drivers/AMDVLK/files/1609371/siege-client-amdvlk.tar.gz)

Output on other drivers:
![siege-client](https://user-images.githubusercontent.com/1669069/34645055-2ce27afe-f3a9-11e7-9916-e1885a879715.png)

**Comment by DominikWitczakAMD** [comment]
We'd appreciate if you could confirm you have run the application with validation enabled and no errors are being reported by any of the validation layers. Thanks.

**Comment by shadiramadan** [comment]
Hi @DominikWitczakAMD, I believe @mikedilger stated in his first post that:
>  LunarG validation reports no issues.

But a confirmation would help clear things up.

**Comment by mikedilger** [comment]
Yes that's right @DominikWitczakAMD @shadiramadan the validation layer does not report any errors (and I have gotten errors from it before so I believe it would report if it had anything to say).  I'm on a different computer in a different office right now, but when I get back to the AMD card I can confirm again.

**Comment by procedural** [comment]
I can confirm too, no validation errors.

**Comment by JacobHeAMD** [comment]
Hi @mikedilger, the depth issue is already fixed by the latest drop. Could you please try again with the latest AMDVLK driver?
I'm debugging the SIGSEGV issue.

**Comment by mikedilger** [comment]
@JacobHeAMD confirmed!  The depth issue is resolved.

**Comment by JacobHeAMD** [comment]
Hi @mikedilger , there is an issue of the application. The memory is allocated for two images, however, the alignment is got according to the first image. And the memoffset for vkBindImageMemory of the second image is not aligned to the alignment required by the second image. And vkBindImageMemory of the second image is failed as a result.
vkBindImageMemory(device = 0x7f8058caf000, image = 0x7f80583d2200, memory = 0x7f80578b9c00, memoryOffset = **2707456**)
memoryOffset should be aligned to 0x8000 (which is returned by vkvkGetImageMemoryRequirements of the second image).

**Comment by procedural** [comment]
Can confirm too, the issue with depth is solved.

![screenshot from 2018-01-10 20-12-41](https://user-images.githubusercontent.com/28234322/34785634-c9e6d4bc-f642-11e7-87f0-c6d6bf256cc9.png)

**Comment by JacobHeAMD** [comment]
Hi @mikedilger, the SIGSEGV issue I mentioned (vkBindImageMemory) before is different from the issue you reported. And it only happens to the "vkreplay -o trace.vktrace". There is no this issue with siege-client. So please ignore it.

**Comment by JacobHeAMD** [comment]
Hi @procedural, thanks for your confirmation.

**Comment by mikedilger** [comment]
Ok so I take it the memory alignment of siege-client was ok.  In particular, from the pastebin trace:
* alignment returned was 4096 (0x1000)
* offset of 2707456 is ok (661 * 4096)
I am then under the impression that under "vkreplay" the card (possibly a different card) requested a different (coarser) alignment, but the replay ignored that and replayed faithfully, giving a SEGV... so not an actual bug.

**Comment by mikedilger** [comment]
Side note: I'm kind of an idiot.  I was using a D16_UNorm depth buffer, not a floating point based one. Reversing the Z without using actual floating point values is pointless.  Anyhow, something to laugh at.

**Comment by JacobHeAMD** [comment]
Another internal ticket is already created for the segfault issue.
