### ISSUE TITLE
Symbol lookup fails in amdvlk64.so

### ISSUE THREAD

**Issue by Themaister** [GPUOpen-Drivers/AMDVLK#41]
Getting this error, and I cannot load the ICD. This seems to be related to the new VK_KHR_display support, but it doesn't seem to be built in.
```
ERROR: [Loader Message] Code 0 : /usr/lib/amdvlk64.so: undefined symbol: _ZN3Pal5Linux19DisplayWindowSystem30DeterminePresentationSupportedEPNS0_6DeviceEPvl
```
Arch Linux's AUR package is doing this:
```
  cmake -H. -Bbuilds/Release64 \
    -DCMAKE_BUILD_TYPE=Release \
    -DBUILD_WAYLAND_SUPPORT=On \
    -DBUILD_WSA=On

  cd builds/Release64
  make
```

**Comment by JacobHeAMD** [comment]
It's supposed to be fixed by commit:aa568df3471787b4bf573780e47c2c625e819c37, please check it. Thanks!
