### ISSUE TITLE
on tahiti doing a 32x16384 copy image on transfer queue can cause hangs

### ISSUE THREAD

**Issue by airlied** [GPUOpen-Drivers/AMDVLK#53]
I was looking into SDMA and Transfer queues and wrote some hacky crucible tests.

One of the tests creates a 32x16384 2D tiled image, and uses the transfer queue to copy it to another 32x16384 2D tiled image. On my tahiti GPU this seems to get some VM faults and a subsequent GPU hang.

**Comment by airlied** [comment]
Even doing image->buffer copies appear to hang.

**Comment by kbiElude** [comment]
Is that a fully-resident image? Any additional create flags that are specified for the image in question?

**Comment by DominikWitczakAMD** [comment]
I can't reproduce the issue, I'm afraid. What I tried doing was an image->image copy of a R8_UNORM 32x16384 2D image using the transfer queue. Everything works fine.

Can you share an api dump / source code showing how to trigger the error, please? Thanks.

**Comment by airlied** [comment]
I was using test code from

https://gitlab.freedesktop.org/airlied/crucible/commits/miptree-rework

The code is a bit rough still I'll try and retest and see if I can still reproduce

**Comment by DominikWitczakAMD** [comment]
Did you mean this: https://gitlab.freedesktop.org/airlied/crucible/blob/miptree-rework/src/tests/func/transfer/transfer_buffer.c ? :-) Thanks.

**Comment by DominikWitczakAMD** [comment]
In specific, please make sure no validation errors are being reported.

**Comment by DominikWitczakAMD** [comment]
Hang on, I'm seeing something interesting. Which HW generation are you using?

**Comment by airlied** [comment]
Yeah gcn 1 and 1.1 si/cik hwm and the miptree tests that us transfer queye
