### ISSUE TITLE
vkcube segfault / assertion failed

### ISSUE THREAD

**Issue by ChristophHaag** [GPUOpen-Drivers/AMDVLK#6]
https://github.com/krh/vkcube
Note that vkcube has at least one known bug: https://github.com/krh/vkcube/issues/25

I'm still making this issue because the assertion seems unrelated.

Running it with a release build segfaults:
```
VK_ICD_FILENAMES=~/amd_icd64.json vkcube
1 physical devices
vendor id 1002, device name AMD Radeon (TM) RX 480 Graphics
[1]    29146 segmentation fault (core dumped)  VK_ICD_FILENAMES=~/amd_icd64.json vkcube
```

Running it with a debug build fails an assertion:
```
vkcube: /home/chris/oldhome/build/amdvlk-git-debug/src/llvm-amdvlk/lib/IR/Instructions.cpp:299: void llvm::CallInst::init(llvm::FunctionType*, llvm::Value*, llvm::ArrayRef<llvm::Value*>, llvm::ArrayRef<llvm::OperandBundleDefT<llvm::Value*> >, const llvm::Twine&): Assertion `(i >= FTy->getNumParams() || FTy->getParamType(i) == Args[i]->getType()) && "Calling a function with a bad signature!"' failed.
```
gdb log with full backtrace: [gdb.txt](https://github.com/GPUOpen-Drivers/AMDVLK/files/1651504/gdb.txt)

**Comment by JacobHeAMD** [comment]
Hi @ChristophHaag , the issue is not seen with the latest driver. Could you please have a try?
