### ISSUE TITLE
Mainline FreeSync / VRR / Adaptive Sync support

### ISSUE THREAD

**Issue by ernstp** [GPUOpen-Drivers/AMDVLK#62]
Add support to AMDVLK for the new mainline FreeSync / VRR api?

Reference:
https://patchwork.freedesktop.org/series/49486/

https://patchwork.freedesktop.org/series/49491/

https://patchwork.freedesktop.org/series/51388/

**Comment by shmerl** [comment]
+1. FreeSync support so far is missing both in radv and amdvlk. Also Wayland use case might need special considerations.

**Comment by debianxfce** [comment]
There is a patch for the RADV freesync support, but non existent gtk4 applications prevents mainlining.
https://gitlab.freedesktop.org/mesa/mesa/merge_requests/596

**Comment by viggy96** [comment]
RADV 19.1 now has FreeSync. Does AMDVLK have this yet?

**Comment by shmerl** [comment]
Just tested with latest amdvlk - adaptive sync still doesn't work.

**Comment by RarogCmex** [comment]
What about now?

**Comment by shmerl** [comment]
I haven't test it lately. Does it work for you?

**Comment by JacobHeAMD** [comment]
Please try with adding "EnableAdaptiveSync,1" to /etc/amd/amdPalSettings.cfg.
