### ISSUE TITLE
GTA V gpu hang during the benchmark scene

### ISSUE THREAD

**Issue by Alexander88207** [GPUOpen-Drivers/AMDVLK#64]
Arch-Linux
AMDVLK : 2.0.63
GPU: AMD RX 570
CPU: AMD FX 8350
Playing this game over Steam Play (Proton 3.16-4+DXVK 0.90)
[-](https://github.com/doitsujin/dxvk/issues/578)
I can not provide an apitrace.

If the jet part comes the full system starts to hang and i had to restart my pc.

**Comment by jinjianrong** [comment]
@Alexander88207, is this an OpenGL game but you run it on top of Vulkan? what middleware do you use?

**Comment by Alexander88207** [comment]
Yeah, i use vulkan (dxvk) & proton 3.16-4 to play this game. i can test it later it in vanilla wine too if this is necessary.

**Comment by jinjianrong** [comment]
@Alexander88207 looks like the hang issue can't be reproduced with latest driver any more, could you help confirm it?

**Comment by Alexander88207** [comment]
https://www.youtube.com/watch?v=5mtKFQIBSvM

**Comment by Alexander88207** [comment]
it is fixed
