### ISSUE TITLE
Artifacts with MSAA on Tahiti cards

### ISSUE THREAD

**Issue by random2324** [GPUOpen-Drivers/AMDVLK#73]
Trying Proton 3.16-6 with latest amdvlk from git produces these strange artifacts:
![deepinbildschirmfoto_20190106113225](https://user-images.githubusercontent.com/19872920/50735437-77e5ab00-11af-11e9-94c1-3989bcfb9353.png)

Vendor: X.Org (0x1002)
    Device: AMD Radeon HD 7900 Series (TAHITI, DRM 3.27.0, 4.20.0-2-amd-staging-drm-next-git, LLVM 8.0.0) (0x6798)
    Version: 19.0.0
    Accelerated: yes
    Video memory: 3072MB
    Unified memory: no
    Preferred profile: core (0x1)
    Max core profile version: 4.5
    Max compat profile version: 4.5
    Max GLES1 profile version: 1.1
    Max GLES[23] profile version: 3.2
Memory info (GL_ATI_meminfo):
    VBO free memory - total: 2608 MB, largest block: 2608 MB
    VBO free aux. memory - total: 3014 MB, largest block: 3014 MB
    Texture free memory - total: 2608 MB, largest block: 2608 MB
    Texture free aux. memory - total: 3014 MB, largest block: 3014 MB
    Renderbuffer free memory - total: 2608 MB, largest block: 2608 MB
    Renderbuffer free aux. memory - total: 3014 MB, largest block: 3014 MB
Memory info (GL_NVX_gpu_memory_info):
    Dedicated video memory: 3072 MB
    Total available memory: 6144 MB
    Currently available dedicated video memory: 2608 MB

Radv just shows me a black screen btw.

**Comment by random2324** [comment]
I tried out some more games. Hitman and Dirt 3. All of those including Project Cars show artifacts when I select  MSAA. This look like a general problem for me on those GCN 1.0 cards.

**Comment by procedural** [comment]
> @JacobHeAMD added wontfix

Why is that? I saw MSAA artifacts on Tahiti on a recent version of AMDVLK too.

**Comment by random2324** [comment]
Switched to Vega so I cant test anymore. Still should be fixed now that GCN1.0 is nearly ready for AMDGPU as default.
