### ISSUE TITLE
Artifacts with DXVK and The Witcher 3

### ISSUE THREAD

**Issue by guglovich** [GPUOpen-Drivers/AMDVLK#74]
Proton 3.16-6 + AMDVLK
https://ibb.co/6R0khXR

Distr: Arch
Kernel: 4.20.0-arch1-1
GPU: RX460

**Comment by shmerl** [comment]
Looks Polaris specific, since it doesn't happen on Vega 56 for me. Does it still occur with latest amdvlk?

**Comment by jiaolu** [comment]
> Looks Polaris specific, since it doesn't happen on Vega 56 for me. Does it still occur with latest amdvlk?

the problem i met is rough edges of shadow miss-casted on the trees on vega.

**Comment by aufkrawall** [comment]
There is still an issue with Polaris and v-2019.Q2.2 with certain foliage before some background objects like distant buildings, the foliage than shows what looks like blocky shadow corruption.

**Comment by nadrolinux** [comment]
Today I tested The Witcher 3 with AMDVLK 2019.Q2.4 and finally it seems that all issues are gone. I have Radeon RX 580.

**Comment by jinjianrong** [comment]
@nadrolinux thanks for the testing
