### ISSUE TITLE
Path of Exile not rendering correctly

### ISSUE THREAD

**Issue by BrosephJ** [GPUOpen-Drivers/AMDVLK#75]
Xubuntu 18.10, Linux Kernel 4.20
Playing with Lutris, DXVK 0.94, Radeon R9 380X

RADV:

![radv](https://user-images.githubusercontent.com/5185864/50906257-90390e00-13d9-11e9-9651-c58ff3757e38.png)

AMDVLK:

![amdvlk](https://user-images.githubusercontent.com/5185864/50906277-9929df80-13d9-11e9-86cf-d78e56288f14.png)

**Comment by montvid** [comment]
got the same problem with the recent amdvlk 2019q1.3. Dxvk 0.96, mesa 19, kernel 4.20, ubuntu 18.04.

**Comment by montvid** [comment]
Sure I can help out! It would be my first time generating a trace. Do you have a wiki on how to do it on Linux, Ubuntu?

It is a popular free game on steam as well on their site 20gb to download. Too dark rendering starts just after starting the game in the character selection screen so no need to play to debug.

**Comment by montvid** [comment]
Oh and the game only starts only with tkg wine used by lutris.

**Comment by Arvamer** [comment]
@jinjianrong  [RenderDoc capture for login screen](https://drive.google.com/open?id=1HkUXPrAR6LQF4gVcSokb326yjkxKiRkP).

**Comment by crystalJinamd** [comment]
@Arvamer hi, Which renderdoc version and asic did you use to capture the trace ? Thanks.

**Comment by Arvamer** [comment]
@crystalJinamd  I used renderdoc 1.2. Sorry I'm not sure what you meant by asic. I captured it on rx 580 using amdvlk built from git (GPUOpen-Drivers/xgl@f2af4b0c33963842f544107d005f0a6c82ea513f).

**Comment by mflayer** [comment]
Hi! I'm having the same issue. It gets to the point where in the darker parts of the game like caves, everything becomes pitch black.
Relevant information: Arch on 5.0.2 kernel, latest amdvlk build from git (via AUR), Radeon R9 280 GPU, renderdoc 1.2-1, playing on Steam with Proton ver. 3.16-8 beta.

Here's a render doc capture from within one of those caves(first time doing it, let me know if you need anything else): [Link, 400MB compressed](https://drive.google.com/file/d/1uADXaAVMrafRw-dP-tnY1DGRLGDjiHH4/view?usp=sharing)

**Comment by mflayer** [comment]
Figured this might be of some importance:
RenderDoc reports multiple issues (13 in my case), severity high. Description is always "Creating renderpass Resourceid::##### contains a subpass dependency that would allow writing indirect command arguments. Indirect command contents are read at the end of the render pass, so write-after-read overwrites will cause incorrect display of indirect arguments." where ##### is a number.
Don't know if this helps.

**Comment by BrosephJ** [comment]
I did the heinous deed of going back to Windows 10 so I am unable to help with this. ;_; Sorry for late response!

**Comment by ernstp** [comment]
Same issue here! Works quite well otherwise.

**Comment by Arvamer** [comment]
I have updated to latest git and it looks like this issue is fixed now.

**Comment by jinjianrong** [comment]
@Arvamer thanks for the update
