### ISSUE TITLE
Broken image in Resident Evil 2 "1-Shot Demo"

### ISSUE THREAD

**Issue by laichiaheng** [GPUOpen-Drivers/AMDVLK#77]
There are lots of blocks in the game.
![2019-01-14 21-09-38](https://user-images.githubusercontent.com/9532105/51114784-4456f080-1841-11e9-8805-822f5fb8c629.png)
Ubuntu 18.04.1
linux4.20
mesa-19.0 (Padoka PPA)

**Comment by JacobHeAMD** [comment]
@laichiaheng , is the issue still seen with the latest amdvlk?

**Comment by jinjianrong** [comment]
Please verify the issue with latest build
