### ISSUE TITLE
Please write a GitHub pull request template containing your requirements.

### ISSUE THREAD

**Issue by floatingatoll** [GPUOpen-Drivers/AMDVLK#78]
Hi, README.md specifies a great deal of pull request requirements that you consider mandatory, however no GitHub pull request template exists in your repository. Please create one, so that users are presented with your pull request requirements each time they create a pull request.

**Comment by Flakebi** [comment]
Hi, what would you add there? I think most of the points [here](https://github.com/GPUOpen-Drivers/AMDVLK#how-to-contribute) are not a great deal and don’t need to be added to the template.

&nbsp;

> The driver is built from source code in four repositories: LLVM, XGL, LLPC and PAL.
> For changes to LLVM, you should submit contribution to the LLVM trunk. Commits there will be evaluated to merge into the amd-vulkan-master branch periodically.

This is helpful to get started but not needed in a pr template imo. I didn’t see anyone opening a pr on the LLVM fork, so no problem there either.
> For changes to XGL, LLPC and PAL, please create a pull request against the dev branch. After your change is reviewed and if it is accepted, it will be evaluated to merge into the master branch in a subsequent regular promotion.

GitHub creates prs automatically agains the dev branch, so this should work without problems.
> IMPORTANT: By creating a pull request, you agree to allow your contribution to be licensed by the project owners under the terms of the MIT License.

This seems obvious, I rarely see repos that require you to sign the MIT License for a pr.
>When contributing to XGL, LLPC and PAL, your code should:
>
>    Match the style of nearby existing code. Your code may be edited to comply with our coding standards when it is merged into the master branch.
>    Avoid adding new dependencies, including dependencies on STL.
>
> Please make each contribution reasonably small. If you would like to make a big contribution, like a new feature or extension, please raise an issue first to allow planning to evaluate and review your work.

I think matching the surrounding style is also obvious (why would you introduce a different style in a pr?).
>    Note: Since PAL is a shared component that must support other APIs, other operating systems, and pre-production hardware, you might be asked to revise your PAL change for reasons that may not be obvious from a pure Linux Vulkan driver perspective.

A contributor will see this from a comment anyway if it should be necessary, so no need to put that into a template.
