### ISSUE TITLE
Performance and rendering problems with Shadow of the Tomb Raider Trial

### ISSUE THREAD

**Issue by debiangamer** [GPUOpen-Drivers/AMDVLK#80]
There is performance (stuttering, loading times)  and rendering problems. The visible line is caused by the screen space reflections setting in the game. Lara has the left arm  black  in the opening scene. I have enabled the AMDVLK shader  disk  cache but with this game the cache is not used.

https://www.youtube.com/watch?v=TrF11YL9lbM

Using AMDVLK from http://repo.radeon.com, wine-4.0 (Staging) and DXVK 0.96.
System:
  Host: ryzenpc Kernel: 5.0.0-rc4 x86_64 bits: 64 Desktop: Xfce 4.12.4 
  Distro: Debian GNU/Linux buster/sid 
Machine:
  Type: Desktop Mobo: ASUSTeK model: PRIME B350M-K v: Rev X.0x 
  serial: <root required> UEFI [Legacy]: American Megatrends v: 4207 
  date: 12/07/2018 
CPU:
  6-Core: AMD Ryzen 5 1600 type: MT MCP speed: 2936 MHz 
Graphics:
  Device-1: AMD Ellesmere [Radeon RX 470/480] driver: amdgpu v: kernel 
  Display: x11 server: X.Org 1.20.3 driver: amdgpu 
  resolution: 3840x2160~60Hz 
  OpenGL: 
  renderer: Radeon RX 570 Series (POLARIS10 DRM 3.27.0 5.0.0-rc4 LLVM 7.0.1) 
  v: 4.5 Mesa 19.0.0-devel (git-7c930d9 2019-01-28 cosmic-oibaf-ppa)

**Comment by JacobHeAMD** [comment]
@debiangamer , could you please try with the latest amdvlk? There was pipeline cache refactory in amdvlk.
