### ISSUE TITLE
Use "amdvlk" in VkPhysicalDeviceDriverPropertiesKHR.driverName

### ISSUE THREAD

**Issue by shmerl** [GPUOpen-Drivers/AMDVLK#81]
Currently, amdvlk is setting [VkPhysicalDeviceDriverPropertiesKHR](https://www.khronos.org/registry/vulkan/specs/1.1-extensions/man/html/VkPhysicalDeviceDriverPropertiesKHR.html).driverName to `AMD open-source driver`. That's not very distinct, given that radv is also open source AMD driver. In fact, radv is using `radv` for that string.

For instance, you can set `VkPhysicalDeviceDriverPropertiesKHR.driverName` to `amdvlk` and `VkPhysicalDeviceDriverPropertiesKHR.driverInfo` to `AMD open-source driver`? The second field is more suitable for longer description, while the first for a short distinctive name.

**Comment by shmerl** [comment]
It's not really too late to do something about it, but may be considering combing values rather than replacing (that if it's even a real concern). amdvlk isn't even used much, so it shouldn't be a big issue how it was for example with browser user agents which evolved into some bulky mess because of such reasons.

**Comment by Anteru** [comment]
The `DriverID` is there to help you discern if it's RADV or AMDVLK: https://www.khronos.org/registry/vulkan/specs/1.1-extensions/man/html/VkDriverIdKHR.html -- is this not sufficient?

**Comment by shmerl** [comment]
That's an interesting source, I can suggest to dxvk to use that.

**Comment by AnzhongHuang** [comment]
@shmerl DXVK already used it.
