### ISSUE TITLE
Would you make packages for Fedora..

### ISSUE THREAD

**Issue by lejeczek** [GPUOpen-Drivers/AMDVLK#86]
..for us lazy ones, that would be fantastic.
many thanks, L.

**Comment by tomkv** [comment]
FYI, there's a package in Fedora copr.

**Comment by cmdrogogov** [comment]
> FYI, there's a package in Fedora copr.

You probably already know this, but It appears the Fedora30 packages failed the build process on this copr repo;

https://copr.fedorainfracloud.org/coprs/tkov/amdvlk/package/amdvlk-vulkan-driver/

**Comment by tomkv** [comment]
Yes, it is failing due to #89, as F30 has gcc9 as it's compiler. The build currently running will also fail. You could try the F29 version (I installed it in F29 and then updated the distro; it still works).

**Comment by samuelig** [comment]
Is there any plan to have official .rpm packages of AMDVLK?

**Comment by JaxLinAMD** [comment]
rpm packages is provided since v-2020.Q3.1 @samuelig

**Comment by samuelig** [comment]
Great, I can confirm it works on a Fedora system. Would it be possible to provide a RPM repo like Ubuntu's? It would be a great idea to avoid installing manually the .rpm packages.

**Comment by JaxLinAMD** [comment]
Sorry, I don't have the plan to set up a server and deploy RPM repo for now :)
