### ISSUE TITLE
Is any plan to support Android(AOSP) build system?

### ISSUE THREAD

**Issue by kenkuang** [GPUOpen-Drivers/AMDVLK#87]
If we try to porting this to AOSP , Does any convenient way to do so ?

**Comment by JarvisToldMeTo** [comment]
Hi kenhuang, i'm interested in it. But can you share with us the purpose of using AMDVLK on android? It seems people rarely using Android with AMD platforms.

**Comment by JaxLinAMD** [comment]
I don't think we have plan for Android System support on Github.
